export default {
  REQUEST_REGISTRATION: 'REQUEST_REGISTRATION',
  REGISTRATION_ERROR: 'REGISTRATION_ERROR',

  REQUEST_LOGGED_IN_USER: 'REQUEST_LOGGED_IN_USER',
  GET_LOGGED_IN_USER_SUCCESS: 'GET_LOGGED_IN_USER_SUCCESS',
  GET_LOGGED_IN_USER_ERROR: 'GET_LOGGED_IN_USER_ERROR',
  LOADED_USER_SUCCESS: 'LOADED_USER_SUCCESS',
  LOADED_USER_FAILURE: 'LOADED_USER_FAILURE',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  REQUEST_LOGOUT: 'REQUEST_LOGOUT',

  REQUEST_LOGIN: 'REQUEST_LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',

  SAVE_NOTIFICATION: 'SAVE_NOTIFICATION',
  SAVE_NOTIFICATION_SUCCESS: 'SAVE_NOTIFICATION_SUCCESS',
  REMOVE_NOTIFICATIONS: 'REMOVE_NOTIFICATIONS',
  REMOVE_NOTIFICATIONS_SUCCESS: 'REMOVE_NOTIFICATIONS_SUCCESS',

  RETRIEVE_LOCATIONS: 'RETRIEVE_LOCATIONS',
  GET_LOCATIONS_SUCCESS: 'GET_LOCATIONS_SUCCESS',
  GET_LOCATIONS_FAILURE: 'GET_LOCATIONS_FAILURE',

  CLEAR_EVENTS: 'CLEAR_EVENTS',
  RETRIEVE_EVENTS: 'RETRIEVE_EVENTS',
  GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
  GET_EVENTS_FAILURE: 'GET_EVENTS_FAILURE',

  RETRIEVE_VENUES: 'RETRIEVE_VENUES',
  GET_VENUES_SUCCESS: 'GET_VENUES_SUCCESS',
  GET_VENUES_FAILURE: 'GET_VENUES_FAILURE',

  RETRIEVE_ARTISTS: 'RETRIEVE_ARTISTS',
  GET_ARTISTS_SUCCESS: 'GET_ARTISTS_SUCCESS',
  GET_ARTISTS_FAILURE: 'GET_ARTISTS_FAILURE',
};
