export default {
  RETRIEVE_LOCATIONS: 'RETRIEVE_LOCATIONS',
  GET_LOCATIONS_SUCCESS: 'GET_LOCATIONS_SUCCESS',
  GET_LOCATIONS_FAILURE: 'GET_LOCATIONS_FAILURE',

  RETRIEVE_EVENTS: 'RETRIEVE_EVENTS',
  GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
  GET_EVENTS_FAILURE: 'GET_EVENTS_FAILURE',

  RETRIEVE_ARTISTS: 'RETRIEVE_ARTISTS',
  GET_ARTISTS_SUCCESS: 'GET_ARTISTS_SUCCESS',
  GET_ARTISTS_FAILURE: 'GET_ARTISTS_FAILURE',
};
