/* eslint-disable quotes */
const artists = [
  { level: 1, name: 'JaRule', url: 'http://bandsintown.com/JaRule' },
  {
    level: 1,
    name: 'a Boogie',
    url: 'http://bandsintown.com/ABOOGIEWITDAHOODIE',
  },
  { level: 1, name: 'Fat Joe', url: 'http://bandsintown.com/FatJoe' },
  {
    level: 1,
    name: 'Waka Flocka',
    url: 'http://bandsintown.com/WakaFlockaFlame',
  },
  { level: 1, name: 'Asap Ferg', url: 'http://bandsintown.com/ASAPFerg' },
  { level: 1, name: 'Shaggy', url: 'http://bandsintown.com/Shaggy' },
  { level: 1, name: 'Ashanti', url: 'http://bandsintown.com/Ashanti' },
  { level: 1, name: 'Young M.A', url: 'http://bandsintown.com/YoungM.A' },
  { level: 1, name: 'Asap Rocky', url: 'http://bandsintown.com/ASAPRocky' },
  { level: 1, name: 'Gucci Mane', url: 'http://bandsintown.com/GucciMane' },
  { level: 1, name: 'Bow Wow', url: 'http://bandsintown.com/BowWow' },
  { level: 1, name: 'Pusha T', url: 'http://bandsintown.com/PushaT' },
  { level: 1, name: 'DMX', url: 'http://bandsintown.com/DMX' },
  { level: 1, name: '21 Savage', url: 'http://bandsintown.com/21Savage' },
  { level: 1, name: 'Ne-Yo', url: 'http://bandsintown.com/Ne-Yo' },
  { level: 1, name: 'Wale', url: 'http://bandsintown.com/Wale' },
  {
    level: 1,
    name: 'Sean Kingston',
    url: 'http://bandsintown.com/SeanKingston',
  },
  { level: 1, name: 'Tyga', url: 'http://bandsintown.com/Tyga' },
  { level: 1, name: 'The LOX', url: 'http://bandsintown.com/TheLOX' },
  { level: 1, name: 'Ace Hood', url: 'http://bandsintown.com/AceHood' },
  { level: 1, name: 'Method Man', url: 'http://bandsintown.com/MethodMan' },
  { level: 1, name: 'Redman', url: 'http://bandsintown.com/Redman' },
  {
    level: 1,
    name: 'Juelz Santana',
    url: 'http://bandsintown.com/JuelzSantana',
  },
  { level: 1, name: 'Jim Jones', url: 'http://bandsintown.com/JimJones' },
  { level: 1, name: 'Mase', url: 'http://bandsintown.com/Mase' },
  { level: 1, name: 'Wyclef Jean', url: 'http://bandsintown.com/WyclefJean' },
  { level: 1, name: 'Ryan Leslie', url: 'http://bandsintown.com/RyanLeslie' },
  { level: 1, name: 'Fabolous', url: 'http://bandsintown.com/Fabolous' },
  { level: 1, name: 'Raekwon', url: 'http://bandsintown.com/Raekwon' },
  { level: 1, name: 'Jadakiss', url: 'http://bandsintown.com/Jadakiss' },
  { level: 1, name: 'N.O.R.E.', url: 'http://bandsintown.com/N.O.R.E.' },
  { level: 1, name: 'Lloyd', url: 'http://bandsintown.com/Lloyd' },
  { level: 1, name: 'Rick Ross', url: 'http://bandsintown.com/RickRoss' },
  { level: 1, name: 'DJ Khaled', url: 'http://bandsintown.com/DJKhaled' },
  { level: 1, name: "Cam'ron", url: "http://bandsintown.com/Cam'ron" },
  {
    level: 1,
    name: 'Chance The Rapper',
    url: 'http://bandsintown.com/ChancetheRapper',
  },
  { level: 1, name: 'Migos', url: 'http://bandsintown.com/Migos' },
  { level: 1, name: 'Lil Yachty', url: 'http://bandsintown.com/LilYachty' },
  {
    level: 1,
    name: 'French Montana',
    url: 'http://bandsintown.com/FrenchMontana',
  },
  {
    level: 1,
    name: 'Soulja Boy',
    url: "http://bandsintown.com/SouljaBoyTell'Em",
  },
  {
    level: 1,
    name: 'The Jillionaire',
    url: 'http://bandsintown.com/TheJillionaire',
  },
];

export default artists;
