/* eslint-disable quotes */
const secondaryArtists = [
  { level: 2, name: '100 Kila', url: 'http://bandsintown.com/100Kila' },
  { level: 2, name: '100s', url: 'http://bandsintown.com/100s' },
  { level: 2, name: '12 Gauge', url: 'http://bandsintown.com/12Gauge' },
  { level: 2, name: '2 Chainz', url: 'http://bandsintown.com/2Chainz' },
  { level: 2, name: '2 Pistols', url: 'http://bandsintown.com/2Pistols' },
  { level: 2, name: '21 Savage', url: 'http://bandsintown.com/21Savage' },
  { level: 2, name: '2Mex', url: 'http://bandsintown.com/2Mex' },
  { level: 2, name: '360', url: 'http://bandsintown.com/360' },
  { level: 2, name: '40 Glocc', url: 'http://bandsintown.com/40Glocc' },
  { level: 2, name: '50 Cent', url: 'http://bandsintown.com/50Cent' },
  {
    level: 2,
    name: 'The 6th Letter',
    url: 'http://bandsintown.com/The6thLetter',
  },
  { level: 2, name: '9th Wonder', url: 'http://bandsintown.com/9thWonder' },
  { level: 2, name: 'Ab-Soul', url: 'http://bandsintown.com/Ab-Soul' },
  {
    level: 2,
    name: 'A Boogie wit da Hoodie',
    url: 'http://bandsintown.com/ABOOGIEWITDAHOODIE',
  },
  {
    level: 2,
    name: 'Abstract Rude',
    url: 'http://bandsintown.com/AbstractRude',
  },
  { level: 2, name: 'Ace Hood', url: 'http://bandsintown.com/AceHood' },
  { level: 2, name: 'Aceyalone', url: 'http://bandsintown.com/Aceyalone' },
  {
    level: 2,
    name: 'Action Bronson',
    url: 'http://bandsintown.com/ActionBronson',
  },
  { level: 2, name: 'Aesop Rock', url: 'http://bandsintown.com/AesopRock' },
  {
    level: 2,
    name: 'Afrika Bambaataa',
    url: 'http://bandsintown.com/AfrikaBambaataa',
  },
  { level: 2, name: 'Afroman', url: 'http://bandsintown.com/Afroman' },
  { level: 2, name: 'Afu-Ra', url: 'http://bandsintown.com/Afu-Ra' },
  { level: 2, name: 'Ahmad', url: 'http://bandsintown.com/Ahmad' },
  { level: 2, name: 'Ajs Nigrutin', url: 'http://bandsintown.com/AjsNigrutin' },
  { level: 2, name: 'Akala', url: 'http://bandsintown.com/Akala' },
  { level: 2, name: 'Akinyele', url: 'http://bandsintown.com/Akinyele' },
  { level: 2, name: 'Akir', url: 'http://bandsintown.com/AKIR' },
  { level: 2, name: 'Akon', url: 'http://bandsintown.com/Akon' },
  {
    level: 2,
    name: 'The Alchemist',
    url: 'http://bandsintown.com/TheAlchemist',
  },
  { level: 2, name: 'Alpha', url: 'http://bandsintown.com/Alpha' },
  { level: 2, name: 'Amadeus', url: 'http://bandsintown.com/Amadeus' },
  { level: 2, name: 'AMG', url: 'http://bandsintown.com/AMG' },
  { level: 2, name: 'Amil', url: 'http://bandsintown.com/Amil' },
  { level: 2, name: 'Aminé', url: 'http://bandsintown.com/Amine' },
  { level: 2, name: 'Amir Obè', url: 'http://bandsintown.com/AmirObè' },
  {
    level: 2,
    name: 'Anderson .Paak',
    url: 'http://bandsintown.com/Anderson.Paak',
  },
  { level: 2, name: 'André 3000', url: 'http://bandsintown.com/André3000' },
  {
    level: 2,
    name: 'Andre Nickatina',
    url: 'http://bandsintown.com/AndreNickatina',
  },
  { level: 2, name: 'Andy Mineo', url: 'http://bandsintown.com/AndyMineo' },
  { level: 2, name: 'Angel Haze', url: 'http://bandsintown.com/AngelHaze' },
  {
    level: 2,
    name: 'Angie Martinez',
    url: 'http://bandsintown.com/AngieMartinez',
  },
  { level: 2, name: 'Ant', url: 'http://bandsintown.com/ANT' },
  { level: 2, name: 'Ant Banks', url: 'http://bandsintown.com/AntBanks' },
  { level: 2, name: 'Antoinette', url: 'http://bandsintown.com/Antoinette' },
  {
    level: 2,
    name: 'Anybody Killa',
    url: 'http://bandsintown.com/AnyBodyKilla',
  },
  { level: 2, name: 'Apache', url: 'http://bandsintown.com/Apache' },
  { level: 2, name: 'Apathy', url: 'http://bandsintown.com/Apathy' },
  { level: 2, name: 'A$AP Ferg', url: 'http://bandsintown.com/ASAPFerg' },
  { level: 2, name: 'A$AP Nast', url: 'http://bandsintown.com/ASAPNast' },
  { level: 2, name: 'A$AP Rocky', url: 'http://bandsintown.com/ASAPRocky' },
  { level: 2, name: 'Asher Roth', url: 'http://bandsintown.com/AsherRoth' },
  {
    level: 2,
    name: 'Astronautalis',
    url: 'http://bandsintown.com/Astronautalis',
  },
  { level: 2, name: 'Awol One', url: 'http://bandsintown.com/AwolOne' },
  { level: 2, name: 'Awkwafina', url: 'http://bandsintown.com/Awkwafina' },
  { level: 2, name: 'AZ', url: 'http://bandsintown.com/A.Z.' },
  {
    level: 2,
    name: 'Azealia Banks',
    url: 'http://bandsintown.com/AzealiaBanks',
  },
  { level: 2, name: 'B-Legit', url: 'http://bandsintown.com/B-Legit' },
  { level: 2, name: 'B-Real', url: 'http://bandsintown.com/BReal' },
  { level: 2, name: 'B.G.', url: 'http://bandsintown.com/B.G.' },
  {
    level: 2,
    name: 'B.G. Knocc Out',
    url: 'http://bandsintown.com/B.G.KnoccOut',
  },
  { level: 2, name: 'B.o.B', url: 'http://bandsintown.com/B.o.B.' },
  { level: 2, name: 'Baby Bash', url: 'http://bandsintown.com/BabyBash' },
  {
    level: 2,
    name: 'Baby Boy da Prince',
    url: 'http://bandsintown.com/BabyBoyDaPrince',
  },
  { level: 2, name: 'Baby D', url: 'http://bandsintown.com/BabyD' },
  { level: 2, name: 'Bad Azz', url: 'http://bandsintown.com/BadAzz' },
  { level: 2, name: 'Badshah', url: 'http://bandsintown.com/BADSHAH' },
  { level: 2, name: 'Baeza', url: 'http://bandsintown.com/Baeza' },
  { level: 2, name: 'Bahamadia', url: 'http://bandsintown.com/Bahamadia' },
  {
    level: 2,
    name: 'Bang Yong-guk',
    url: 'http://bandsintown.com/BangYongGuk',
  },
  { level: 2, name: 'Bangladesh', url: 'http://bandsintown.com/Bangladesh' },
  { level: 2, name: 'Bas', url: 'http://bandsintown.com/Bas' },
  { level: 2, name: 'Battlecat', url: 'http://bandsintown.com/Battlecat' },
  { level: 2, name: 'Beanie Sigel', url: 'http://bandsintown.com/BeanieSigel' },
  { level: 2, name: 'Becky G', url: 'http://bandsintown.com/BeckyG' },
  { level: 2, name: 'Benny Blanco', url: 'http://bandsintown.com/BennyBlanko' },
  { level: 2, name: 'Beenzino', url: 'http://bandsintown.com/Beenzino' },
  { level: 2, name: 'Benzino', url: 'http://bandsintown.com/Benzino' },
  { level: 2, name: 'Big Boi', url: 'http://bandsintown.com/BigBoi' },
  {
    level: 2,
    name: 'Big Daddy Kane[1]',
    url: 'http://bandsintown.com/BigDaddyKane',
  },
  { level: 2, name: 'Big Gipp', url: 'http://bandsintown.com/BigGipp' },
  { level: 2, name: 'Big Hawk', url: 'http://bandsintown.com/BigHawk' },
  { level: 2, name: 'Big K.R.I.T.', url: 'http://bandsintown.com/BigK.R.I.T.' },
  {
    level: 2,
    name: 'Big Kuntry King',
    url: 'http://bandsintown.com/BigKuntryKing',
  },
  { level: 2, name: 'Big L', url: 'http://bandsintown.com/BigL' },
  { level: 2, name: 'Big Mike', url: 'http://bandsintown.com/BigMike' },
  { level: 2, name: 'Big Moe', url: 'http://bandsintown.com/BigMoe' },
  { level: 2, name: 'Big Noyd', url: 'http://bandsintown.com/BigNoyd' },
  { level: 2, name: 'Big Pokey', url: 'http://bandsintown.com/BigPokey' },
  { level: 2, name: 'Big Pooh', url: 'http://bandsintown.com/RapperBigPooh' },
  { level: 2, name: 'Big Scoob', url: 'http://bandsintown.com/BigScoob' },
  { level: 2, name: 'Big Sean', url: 'http://bandsintown.com/BigSean' },
  { level: 2, name: 'Big Shug', url: 'http://bandsintown.com/BigShug' },
  { level: 2, name: 'Big Syke', url: 'http://bandsintown.com/BigSyke' },
  { level: 2, name: 'Billy Woods', url: 'http://bandsintown.com/BillyWoods' },
  { level: 2, name: 'Birdman', url: 'http://bandsintown.com/Birdman' },
  { level: 2, name: 'Bishop Nehru', url: 'http://bandsintown.com/BishopNehru' },
  { level: 2, name: 'Biz Markie[2]', url: 'http://bandsintown.com/BizMarkie' },
  { level: 2, name: 'Bizarre', url: 'http://bandsintown.com/Bizarre' },
  { level: 2, name: 'Bizzy', url: 'http://bandsintown.com/Bizzy' },
  { level: 2, name: 'Bizzy Bone', url: 'http://bandsintown.com/BizzyBone' },
  {
    level: 2,
    name: 'BJ the Chicago Kid',
    url: 'http://bandsintown.com/BJTheChicagoKid',
  },
  { level: 2, name: 'Black Milk', url: 'http://bandsintown.com/BlackMilk' },
  { level: 2, name: 'Black Rob', url: 'http://bandsintown.com/BlackRob' },
  {
    level: 2,
    name: 'Black Thought',
    url: 'http://bandsintown.com/BlackThought',
  },
  {
    level: 2,
    name: 'Blaze Ya Dead Homie',
    url: 'http://bandsintown.com/Blaze-YaDeadHomie',
  },
  { level: 2, name: 'Blood Raw', url: 'http://bandsintown.com/BloodRaw' },
  { level: 2, name: 'Blu', url: 'http://bandsintown.com/Blu' },
  {
    level: 2,
    name: 'Bobby Brackins',
    url: 'http://bandsintown.com/BobbyBrackins',
  },
  {
    level: 2,
    name: 'Bobby Creekwater',
    url: 'http://bandsintown.com/BobbyCreekwater',
  },
  {
    level: 2,
    name: 'Bobby Shmurda',
    url: 'http://bandsintown.com/BobbyShmurda',
  },
  { level: 2, name: 'Boi-1da', url: 'http://bandsintown.com/Boi-1da' },
  { level: 2, name: 'Boldy James', url: 'http://bandsintown.com/BoldyJames' },
  { level: 2, name: 'Bone Crusher', url: 'http://bandsintown.com/BoneCrusher' },
  { level: 2, name: 'Booba', url: 'http://bandsintown.com/Booba' },
  {
    level: 2,
    name: 'Boosie Badazz',
    url: 'http://bandsintown.com/BoosieBadazz',
  },
  { level: 2, name: 'Boss', url: 'http://bandsintown.com/B.O.S.S.' },
  { level: 2, name: 'Bow Wow[1]', url: 'http://bandsintown.com/BowWow' },
  { level: 2, name: 'Braille', url: 'http://bandsintown.com/Braille' },
  {
    level: 2,
    name: 'Brandun DeShay',
    url: 'http://bandsintown.com/brandundeshay',
  },
  {
    level: 2,
    name: 'Brianna Perry',
    url: 'http://bandsintown.com/BriannaPerry',
  },
  { level: 2, name: 'Brisco', url: 'http://bandsintown.com/Brisco' },
  {
    level: 2,
    name: 'Brotha Lynch Hung',
    url: 'http://bandsintown.com/BrothaLynchHung',
  },
  { level: 2, name: 'Brother Ali', url: 'http://bandsintown.com/BrotherAli' },
  {
    level: 2,
    name: 'Bryson Tiller',
    url: 'http://bandsintown.com/BrysonTiller',
  },
  {
    level: 2,
    name: 'Bubba Sparxxx',
    url: 'http://bandsintown.com/BubbaSparxxx',
  },
  { level: 2, name: 'Buckshot', url: 'http://bandsintown.com/Buckshot' },
  { level: 2, name: 'Buckwild', url: 'http://bandsintown.com/Buckwild' },
  {
    level: 2,
    name: 'Bumpy Knuckles',
    url: 'http://bandsintown.com/BumpyKnuckles',
  },
  { level: 2, name: 'Bun B', url: 'http://bandsintown.com/BunB' },
  { level: 2, name: 'Busdriver', url: 'http://bandsintown.com/Busdriver' },
  {
    level: 2,
    name: 'Bushwick Bill',
    url: 'http://bandsintown.com/BushwickBill',
  },
  {
    level: 2,
    name: 'Busta Rhymes[2]',
    url: 'http://bandsintown.com/BustaRhymes',
  },
  {
    level: 2,
    name: 'Butch Cassidy',
    url: 'http://bandsintown.com/ButchCassidy',
  },
  { level: 2, name: 'C-Bo', url: 'http://bandsintown.com/C-Bo' },
  { level: 2, name: 'C-Murder', url: 'http://bandsintown.com/C-Murder' },
  { level: 2, name: 'C-Note', url: 'http://bandsintown.com/C-Note' },
  { level: 2, name: 'C-Rayz Walz', url: 'http://bandsintown.com/C-RayzWalz' },
  { level: 2, name: 'Cage', url: 'http://bandsintown.com/CAGE' },
  { level: 2, name: "Cam'ron", url: "http://bandsintown.com/Cam'ron" },
  { level: 2, name: 'Canibus', url: 'http://bandsintown.com/Canibus' },
  {
    level: 2,
    name: 'Capital Steez',
    url: 'http://bandsintown.com/CapitalSteez',
  },
  { level: 2, name: 'Capone', url: 'http://bandsintown.com/Capone' },
  { level: 2, name: 'Cappadonna', url: 'http://bandsintown.com/Cappadonna' },
  { level: 2, name: 'Cardi B', url: 'http://bandsintown.com/CardiB' },
  {
    level: 2,
    name: 'Casey Veggies',
    url: 'http://bandsintown.com/CaseyVeggies',
  },
  { level: 2, name: 'Cash Out', url: 'http://bandsintown.com/CashOut' },
  { level: 2, name: 'Caskey', url: 'http://bandsintown.com/Caskey' },
  {
    level: 2,
    name: 'Casper Nyovest',
    url: 'http://bandsintown.com/CassperNyovest',
  },
  { level: 2, name: 'Cassidy', url: 'http://bandsintown.com/Cassidy' },
  { level: 2, name: 'Cazwell', url: 'http://bandsintown.com/Cazwell' },
  { level: 2, name: 'CeeLo Green', url: 'http://bandsintown.com/Cee-Lo' },
  { level: 2, name: 'Celly Cel', url: 'http://bandsintown.com/CellyCel' },
  { level: 2, name: 'Celph Titled', url: 'http://bandsintown.com/CelphTitled' },
  { level: 2, name: 'Ceza', url: 'http://bandsintown.com/Ceza' },
  {
    level: 2,
    name: 'Chamillionaire',
    url: 'http://bandsintown.com/Chamillionaire',
  },
  {
    level: 2,
    name: 'Chance the Rapper',
    url: 'http://bandsintown.com/ChancetheRapper',
  },
  {
    level: 2,
    name: 'Chanel West Coast',
    url: 'http://bandsintown.com/ChanelWestCoast',
  },
  { level: 2, name: 'Charizma', url: 'http://bandsintown.com/Charizma' },
  {
    level: 2,
    name: 'Charles Hamilton',
    url: 'http://bandsintown.com/CharlesHamilton',
  },
  {
    level: 2,
    name: 'Charli Baltimore',
    url: 'http://bandsintown.com/CharliBaltimore',
  },
  { level: 2, name: 'Chevy Woods', url: 'http://bandsintown.com/ChevyWoods' },
  { level: 2, name: 'Chiddy Bang', url: 'http://bandsintown.com/ChiddyBang' },
  { level: 2, name: 'Chief Keef', url: 'http://bandsintown.com/ChiefKeef' },
  {
    level: 2,
    name: 'Childish Gambino',
    url: 'http://bandsintown.com/ChildishGambino',
  },
  { level: 2, name: 'Chingy[1]', url: 'http://bandsintown.com/Chingy' },
  { level: 2, name: 'Chingo Bling', url: 'http://bandsintown.com/ChingoBling' },
  { level: 2, name: 'Chino XL', url: 'http://bandsintown.com/ChinoXL' },
  { level: 2, name: 'Chinx', url: 'http://bandsintown.com/CHINX' },
  { level: 2, name: 'Chip', url: 'http://bandsintown.com/Chip' },
  { level: 2, name: 'Choice', url: 'http://bandsintown.com/Choice' },
  { level: 2, name: 'Choppa', url: 'http://bandsintown.com/Choppa' },
  { level: 2, name: 'Chris Brown', url: 'http://bandsintown.com/ChrisBrown' },
  { level: 2, name: 'Chris Webby', url: 'http://bandsintown.com/ChrisWebby' },
  {
    level: 2,
    name: 'Christopher Martin',
    url: 'http://bandsintown.com/ChristopherMartin',
  },
  { level: 2, name: 'Chubb Rock', url: 'http://bandsintown.com/ChubbRock' },
  { level: 2, name: 'CJ Fly', url: 'http://bandsintown.com/CJFLY' },
  { level: 2, name: 'CL', url: 'http://bandsintown.com/CL' },
  { level: 2, name: 'CL Smooth', url: 'http://bandsintown.com/C.L.Smooth' },
  { level: 2, name: 'Classified', url: 'http://bandsintown.com/Classified' },
  {
    level: 2,
    name: 'Clinton Sparks',
    url: 'http://bandsintown.com/ClintonSparks',
  },
  { level: 2, name: 'Clyde Carson', url: 'http://bandsintown.com/ClydeCarson' },
  { level: 2, name: 'Common[1]', url: 'http://bandsintown.com/Common' },
  { level: 2, name: 'Consequence', url: 'http://bandsintown.com/Consequence' },
  { level: 2, name: 'Cool Breeze', url: 'http://bandsintown.com/CoolBreeze' },
  { level: 2, name: 'Coolio', url: 'http://bandsintown.com/Coolio' },
  { level: 2, name: 'Copywrite', url: 'http://bandsintown.com/Copywrite' },
  { level: 2, name: 'Cormega', url: 'http://bandsintown.com/Cormega' },
  { level: 2, name: 'Cory Gunz', url: 'http://bandsintown.com/CoryGunz' },
  { level: 2, name: 'Count Bass D', url: 'http://bandsintown.com/CountBassD' },
  { level: 2, name: 'The Coup', url: 'http://bandsintown.com/TheCoup' },
  { level: 2, name: 'Craig Mack', url: 'http://bandsintown.com/CraigMack' },
  { level: 2, name: 'Crooked I', url: 'http://bandsintown.com/CrookedI' },
  { level: 2, name: 'Cupcakke', url: 'http://bandsintown.com/CupcakKe' },
  { level: 2, name: 'Currensy', url: 'http://bandsintown.com/Curren$y' },
  {
    level: 2,
    name: 'Cyhi the Prynce',
    url: 'http://bandsintown.com/CyHiThePrynce',
  },
  { level: 2, name: "D'Angelo", url: "http://bandsintown.com/D'Angelo" },
  { level: 2, name: "D'banj", url: "http://bandsintown.com/D'banj" },
  { level: 2, name: 'D-Loc', url: 'http://bandsintown.com/D-Loc' },
  { level: 2, name: 'D-Nice', url: 'http://bandsintown.com/D-Nice' },
  { level: 2, name: 'D-Pryde', url: 'http://bandsintown.com/DPryde' },
  { level: 2, name: 'Da Brat', url: 'http://bandsintown.com/DaBrat' },
  { level: 2, name: 'Da$h', url: 'http://bandsintown.com/Da$h' },
  { level: 2, name: 'Dae Dae', url: 'http://bandsintown.com/DaeDae' },
  {
    level: 2,
    name: 'Damu the Fudgemunk',
    url: 'http://bandsintown.com/DamutheFudgemunk',
  },
  { level: 2, name: 'Dan Bull', url: 'http://bandsintown.com/DanBull' },
  { level: 2, name: 'Dana Dane', url: 'http://bandsintown.com/DanaDane' },
  { level: 2, name: 'Danny Boy', url: 'http://bandsintown.com/DannyBoy' },
  { level: 2, name: 'Danny Brown', url: 'http://bandsintown.com/DannyBrown' },
  { level: 2, name: 'Dappy', url: 'http://bandsintown.com/Dappy' },
  { level: 2, name: 'Dave East', url: 'http://bandsintown.com/DaveEast' },
  { level: 2, name: 'Daveed Diggs', url: 'http://bandsintown.com/DaveedDiggs' },
  { level: 2, name: 'David Banner', url: 'http://bandsintown.com/DavidBanner' },
  { level: 2, name: 'David Dallas', url: 'http://bandsintown.com/DavidDallas' },
  { level: 2, name: 'David Rush', url: 'http://bandsintown.com/DavidRush' },
  {
    level: 2,
    name: 'Daz Dillinger',
    url: 'http://bandsintown.com/DazDillinger',
  },
  { level: 2, name: 'Dej Loaf', url: 'http://bandsintown.com/DejLoaf' },
  {
    level: 2,
    name: 'Delyric Oracle',
    url: 'http://bandsintown.com/DelyricOracle',
  },
  {
    level: 2,
    name: 'Del the Funky Homosapien',
    url: 'http://bandsintown.com/DelTheFunkyHomosapien',
  },
  { level: 2, name: 'Demrick', url: 'http://bandsintown.com/Demrick' },
  {
    level: 2,
    name: 'Deniro Farrar',
    url: 'http://bandsintown.com/DeniroFarrar',
  },
  { level: 2, name: 'Denzel Curry', url: 'http://bandsintown.com/DenzelCurry' },
  { level: 2, name: 'Derek Minor', url: 'http://bandsintown.com/DerekMinor' },
  { level: 2, name: 'Desiigner', url: 'http://bandsintown.com/Desiigner' },
  { level: 2, name: 'Detail', url: 'http://bandsintown.com/Detail' },
  { level: 2, name: 'Deuce', url: 'http://bandsintown.com/Deuce' },
  { level: 2, name: 'Dev', url: 'http://bandsintown.com/Dev' },
  {
    level: 2,
    name: 'Devin the Dude',
    url: 'http://bandsintown.com/DevintheDude',
  },
  { level: 2, name: 'Devlin', url: 'http://bandsintown.com/Devlin' },
  { level: 2, name: 'Diabolic', url: 'http://bandsintown.com/Diabolic' },
  { level: 2, name: 'Diamond', url: 'http://bandsintown.com/Diamond' },
  { level: 2, name: 'Diamond D', url: 'http://bandsintown.com/DiamondD' },
  {
    level: 2,
    name: 'Diggy Simmons',
    url: 'http://bandsintown.com/DiggySimmons',
  },
  {
    level: 2,
    name: 'Dillon Cooper',
    url: 'http://bandsintown.com/DillonCooper',
  },
  {
    level: 2,
    name: 'Dizzee Rascal',
    url: 'http://bandsintown.com/DizzeeRascal!',
  },
  { level: 2, name: 'Dizzy Wright', url: 'http://bandsintown.com/DizzyWright' },
  {
    level: 2,
    name: 'DJ Cash Money',
    url: 'http://bandsintown.com/DJCashMoney',
  },
  { level: 2, name: 'DJ Casper', url: 'http://bandsintown.com/DJCasper' },
  { level: 2, name: 'DJ Clay', url: 'http://bandsintown.com/DJClay' },
  { level: 2, name: 'DJ Clue?', url: 'http://bandsintown.com/DJCLUE' },
  { level: 2, name: 'DJ Drama', url: 'http://bandsintown.com/DJDrama' },
  { level: 2, name: 'DJ Felli Fel', url: 'http://bandsintown.com/DJFelliFel' },
  {
    level: 2,
    name: 'DJ Green Lantern',
    url: 'http://bandsintown.com/DJGreenLantern',
  },
  { level: 2, name: 'DJ Hurricane', url: 'http://bandsintown.com/DJHurricane' },
  { level: 2, name: 'DJ Kay Slay', url: 'http://bandsintown.com/DJKaySlay' },
  { level: 2, name: 'DJ Khaled', url: 'http://bandsintown.com/DJKhaled' },
  { level: 2, name: 'DJ Krush', url: 'http://bandsintown.com/DJKrush' },
  { level: 2, name: 'DJ Mustard', url: 'http://bandsintown.com/DJMustard' },
  { level: 2, name: 'DJ Paul', url: 'http://bandsintown.com/DJPaul' },
  { level: 2, name: 'DJ Premier', url: 'http://bandsintown.com/DJPremier' },
  { level: 2, name: 'DJ Quik', url: 'http://bandsintown.com/DJQuik' },
  { level: 2, name: 'DJ Screw', url: 'http://bandsintown.com/DJScrew' },
  { level: 2, name: 'DJ Shadow', url: 'http://bandsintown.com/DJShadow' },
  { level: 2, name: 'DJ Yella', url: 'http://bandsintown.com/DJYella' },
  { level: 2, name: 'DMX[1]', url: 'http://bandsintown.com/DMX' },
  { level: 2, name: 'Doap Nixon', url: 'http://bandsintown.com/DoapNixon' },
  { level: 2, name: 'Doe B', url: 'http://bandsintown.com/DoeB' },
  { level: 2, name: 'Dok2', url: 'http://bandsintown.com/Dok2' },
  { level: 2, name: 'Dolla', url: 'http://bandsintown.com/Dolla' },
  { level: 2, name: 'Dom Kennedy', url: 'http://bandsintown.com/DomKennedy' },
  {
    level: 2,
    name: 'Dominique Young Unique',
    url: 'http://bandsintown.com/DominiqueYoungUnique',
  },
  { level: 2, name: 'Domo Genesis', url: 'http://bandsintown.com/DomoGenesis' },
  { level: 2, name: 'Don Cannon', url: 'http://bandsintown.com/DJDonCannon' },
  { level: 2, name: 'Dorrough', url: 'http://bandsintown.com/Dorrough' },
  { level: 2, name: 'Doseone', url: 'http://bandsintown.com/Doseone' },
  {
    level: 2,
    name: 'Doug E. Fresh',
    url: 'http://bandsintown.com/DougE.Fresh',
  },
  { level: 2, name: 'Doughbeezy', url: 'http://bandsintown.com/Doughbeezy' },
  { level: 2, name: 'Dr. Dre[2]', url: 'http://bandsintown.com/DrDre' },
  { level: 2, name: 'Drag-On', url: 'http://bandsintown.com/Drag-On' },
  { level: 2, name: 'Drake[2]', url: 'http://bandsintown.com/Drake' },
  { level: 2, name: 'Dres', url: 'http://bandsintown.com/DJDRES' },
  { level: 2, name: 'Drew Deezy', url: 'http://bandsintown.com/DrewDeezy' },
  {
    level: 2,
    name: 'Driicky Graham',
    url: 'http://bandsintown.com/DriickyGraham',
  },
  { level: 2, name: 'Droop-E', url: 'http://bandsintown.com/Droop-E' },
  { level: 2, name: 'Dru Down', url: 'http://bandsintown.com/DruDown' },
  { level: 2, name: 'Drumma Boy', url: 'http://bandsintown.com/DrummaBoy' },
  {
    level: 2,
    name: 'Dumbfoundead',
    url: 'http://bandsintown.com/Dumbfoundead',
  },
  { level: 2, name: 'E-40', url: 'http://bandsintown.com/E-40' },
  { level: 2, name: 'E.S.G.', url: 'http://bandsintown.com/ESG' },
  {
    level: 2,
    name: 'Earl Sweatshirt',
    url: 'http://bandsintown.com/EarlSweatshirt',
  },
  { level: 2, name: 'Eazy-E', url: 'http://bandsintown.com/Eazy-E' },
  { level: 2, name: 'Ed O.G.', url: 'http://bandsintown.com/EdO.G.' },
  { level: 2, name: 'Edo Maajka', url: 'http://bandsintown.com/EdoMaajka' },
  { level: 2, name: 'El Da Sensei', url: 'http://bandsintown.com/EldaSensei' },
  { level: 2, name: 'El-P', url: 'http://bandsintown.com/El-P' },
  { level: 2, name: 'Elephant Man', url: 'http://bandsintown.com/ElephantMan' },
  { level: 2, name: 'Elzhi', url: 'http://bandsintown.com/Elzhi' },
  { level: 2, name: 'Eminem[1]', url: 'http://bandsintown.com/eminem' },
  {
    level: 2,
    name: 'Eric Biddines',
    url: 'http://bandsintown.com/EricBiddines',
  },
  { level: 2, name: 'Erick Sermon', url: 'http://bandsintown.com/ErickSermon' },
  { level: 2, name: 'Eric Stanley', url: 'http://bandsintown.com/EricStanley' },
  { level: 2, name: 'Esham', url: 'http://bandsintown.com/Esham' },
  { level: 2, name: 'Esoteric', url: 'http://bandsintown.com/Esoteric' },
  { level: 2, name: 'Eve', url: 'http://bandsintown.com/EVE' },
  { level: 2, name: 'Evidence', url: 'http://bandsintown.com/Evidence' },
  { level: 2, name: 'Eyedea', url: 'http://bandsintown.com/Eyedea' },
  { level: 2, name: 'Fabolous', url: 'http://bandsintown.com/Fabolous' },
  { level: 2, name: 'Fabri Fibra', url: 'http://bandsintown.com/FabriFibra' },
  { level: 2, name: 'Fam-Lay', url: 'http://bandsintown.com/Fam-Lay' },
  { level: 2, name: 'Fashawn', url: 'http://bandsintown.com/Fashawn' },
  { level: 2, name: 'Fat Joe', url: 'http://bandsintown.com/FatJoe' },
  { level: 2, name: 'Fat Pat', url: 'http://bandsintown.com/FatPat' },
  { level: 2, name: 'Fat Trel', url: 'http://bandsintown.com/FatTrel' },
  { level: 2, name: 'Father MC', url: 'http://bandsintown.com/FatherMC' },
  { level: 2, name: 'Fatman Scoop', url: 'http://bandsintown.com/FatmanScoop' },
  { level: 2, name: 'Fergie', url: 'http://bandsintown.com/Fergie' },
  { level: 2, name: 'Fetty Wap', url: 'http://bandsintown.com/FettyWap' },
  { level: 2, name: 'Fiend', url: 'http://bandsintown.com/Fiend' },
  { level: 2, name: 'FLAME', url: 'http://bandsintown.com/Flame' },
  { level: 2, name: 'Flavor Flav', url: 'http://bandsintown.com/FlavorFlav' },
  { level: 2, name: 'Flo Rida', url: 'http://bandsintown.com/FloRida' },
  { level: 2, name: 'Flying Lotus', url: 'http://bandsintown.com/FlyingLotus' },
  { level: 2, name: 'Focus...', url: 'http://bandsintown.com/Focus' },
  {
    level: 2,
    name: 'Fonzworth Bentley',
    url: 'http://bandsintown.com/FonzworthBentley',
  },
  { level: 2, name: 'Fort Minor', url: 'http://bandsintown.com/FortWorth' },
  { level: 2, name: 'Foxx', url: 'http://bandsintown.com/Foxx' },
  { level: 2, name: 'Foxy Brown', url: 'http://bandsintown.com/FoxyBrown' },
  { level: 2, name: 'Frank Ocean', url: 'http://bandsintown.com/FrankOcean' },
  { level: 2, name: 'Frankie J', url: 'http://bandsintown.com/FrankieJ' },
  { level: 2, name: 'Frayser Boy', url: 'http://bandsintown.com/FrayserBoy' },
  { level: 2, name: 'Freak Nasty', url: 'http://bandsintown.com/FreakNasty' },
  {
    level: 2,
    name: 'Freddie Foxxx',
    url: 'http://bandsintown.com/FreddieFoxxx',
  },
  {
    level: 2,
    name: 'Freddie Gibbs',
    url: 'http://bandsintown.com/FreddieGibbs',
  },
  {
    level: 2,
    name: 'Fredo Santana',
    url: 'http://bandsintown.com/Fredosantana',
  },
  { level: 2, name: 'Fredro Starr', url: 'http://bandsintown.com/FredroStarr' },
  { level: 2, name: 'Free', url: 'http://bandsintown.com/Free' },
  {
    level: 2,
    name: 'Freekey Zekey',
    url: 'http://bandsintown.com/FreekeyZeekey',
  },
  { level: 2, name: 'Freeway', url: 'http://bandsintown.com/Freeway' },
  {
    level: 2,
    name: 'French Montana',
    url: 'http://bandsintown.com/FrenchMontana',
  },
  { level: 2, name: 'Frenkie', url: 'http://bandsintown.com/Frenkie' },
  { level: 2, name: 'Froggy Fresh', url: 'http://bandsintown.com/FroggyFresh' },
  {
    level: 2,
    name: 'Funkmaster Flex',
    url: 'http://bandsintown.com/FunkmasterFlex',
  },
  { level: 2, name: 'Future', url: 'http://bandsintown.com/Future' },
  { level: 2, name: 'G-Dragon', url: 'http://bandsintown.com/G-Dragon' },
  { level: 2, name: 'G-Eazy', url: 'http://bandsintown.com/G-Eazy' },
  { level: 2, name: 'G. Dep', url: 'http://bandsintown.com/G.Dep' },
  { level: 2, name: 'Gaeko', url: 'http://bandsintown.com/Gaeko' },
  { level: 2, name: 'The Game', url: 'http://bandsintown.com/TheGame' },
  { level: 2, name: 'Gangsta Boo', url: 'http://bandsintown.com/GangstaBoo' },
  { level: 2, name: 'Ganksta N-I-P', url: 'http://bandsintown.com/GankstaG' },
  {
    level: 2,
    name: 'Ghostface Killah[1]',
    url: 'http://bandsintown.com/GhostfaceKillah',
  },
  { level: 2, name: 'Giggs', url: 'http://bandsintown.com/Giggs' },
  {
    level: 2,
    name: 'Gilbere Forte',
    url: 'http://bandsintown.com/GilbereForte',
  },
  {
    level: 2,
    name: 'Glasses Malone',
    url: 'http://bandsintown.com/GlassesMalone',
  },
  { level: 2, name: 'GLC', url: 'http://bandsintown.com/GLC' },
  { level: 2, name: 'Goldie Loc', url: 'http://bandsintown.com/GoldieLoc' },
  { level: 2, name: 'GoldLink', url: 'http://bandsintown.com/Goldlink' },
  { level: 2, name: 'Gorilla Zoe', url: 'http://bandsintown.com/GorillaZoe' },
  { level: 2, name: 'Grafh', url: 'http://bandsintown.com/Grafh' },
  { level: 2, name: 'Grand Puba', url: 'http://bandsintown.com/GrandPuba' },
  {
    level: 2,
    name: 'Grandmaster Caz',
    url: 'http://bandsintown.com/GrandmasterCaz',
  },
  {
    level: 2,
    name: 'Grandmaster Flash[1]',
    url: 'http://bandsintown.com/GrandmasterFlash',
  },
  {
    level: 2,
    name: 'Greydon Square',
    url: 'http://bandsintown.com/GreydonSquare',
  },
  { level: 2, name: 'Gucci Mane', url: 'http://bandsintown.com/GucciMane' },
  { level: 2, name: 'Gudda Gudda', url: 'http://bandsintown.com/GuddaGudda' },
  {
    level: 2,
    name: 'Guerilla Black',
    url: 'http://bandsintown.com/GuerillaBlack',
  },
  {
    level: 2,
    name: 'Guilty Simpson',
    url: 'http://bandsintown.com/GuiltySimpson',
  },
  { level: 2, name: 'Gunplay', url: 'http://bandsintown.com/Gunplay' },
  { level: 2, name: 'Guru[1]', url: 'http://bandsintown.com/Guru' },
  { level: 2, name: 'GZA', url: 'http://bandsintown.com/TheGZA' },
  { level: 2, name: 'Hard Kaur', url: 'http://bandsintown.com/HardKaur' },
  { level: 2, name: 'Hasan Salaam', url: 'http://bandsintown.com/HasanSalaam' },
  { level: 2, name: 'Havoc', url: 'http://bandsintown.com/Havoc' },
  { level: 2, name: 'Heavy D', url: 'http://bandsintown.com/HeavyD' },
  { level: 2, name: 'Heize', url: 'http://bandsintown.com/HEIZE' },
  {
    level: 2,
    name: 'Hemlock Ernst',
    url: 'http://bandsintown.com/HemlockErnst',
  },
  { level: 2, name: 'Hi-C', url: 'http://bandsintown.com/Hi-C' },
  { level: 2, name: 'Hi-Tek', url: 'http://bandsintown.com/Hi-Tek' },
  { level: 2, name: 'Hit-Boy', url: 'http://bandsintown.com/HitBoy' },
  { level: 2, name: 'Hodgy Beats', url: 'http://bandsintown.com/HodgyBeats' },
  {
    level: 2,
    name: 'Honey Cocaine',
    url: 'http://bandsintown.com/HoneyCocaine',
  },
  { level: 2, name: 'Hoodie Allen', url: 'http://bandsintown.com/HoodieAllen' },
  { level: 2, name: 'Hopsin', url: 'http://bandsintown.com/Hopsin' },
  { level: 2, name: 'Huey', url: 'http://bandsintown.com/Huey' },
  {
    level: 2,
    name: 'Hurricane Chris',
    url: 'http://bandsintown.com/HurricaneChris',
  },
  { level: 2, name: 'Hush', url: 'http://bandsintown.com/Hush' },
  {
    level: 2,
    name: 'Hussein Fatal',
    url: 'http://bandsintown.com/HusseinFatal',
  },
  { level: 2, name: 'Ice Cube[1]', url: 'http://bandsintown.com/IceCube' },
  { level: 2, name: 'Ice-T[2]', url: 'http://bandsintown.com/Ice-T' },
  { level: 2, name: 'Iggy Azalea', url: 'http://bandsintown.com/IggyAzalea' },
  { level: 2, name: 'Illmind', url: 'http://bandsintown.com/Illmind' },
  {
    level: 2,
    name: 'ILoveMakonnen',
    url: 'http://bandsintown.com/Ilovemakonnen',
  },
  {
    level: 2,
    name: 'Immortal Technique',
    url: 'http://bandsintown.com/ImmortalTechnique',
  },
  { level: 2, name: 'Imran Khan', url: 'http://bandsintown.com/ImranKhan' },
  {
    level: 2,
    name: 'Inspectah Deck',
    url: 'http://bandsintown.com/InspectahDeck',
  },
  {
    level: 2,
    name: 'Isaiah Rashad',
    url: 'http://bandsintown.com/IsaiahRashad',
  },
  { level: 2, name: 'Iyanya', url: 'http://bandsintown.com/Iyanya' },
  { level: 2, name: 'Iyaz', url: 'http://bandsintown.com/Iyaz' },
  { level: 2, name: 'J Dilla', url: 'http://bandsintown.com/JDilla' },
  { level: 2, name: 'J-Diggs', url: 'http://bandsintown.com/J-Diggs' },
  { level: 2, name: 'J-Kwon', url: 'http://bandsintown.com/J-Kwon' },
  { level: 2, name: 'J-Son', url: 'http://bandsintown.com/J-Son' },
  { level: 2, name: 'J. Cole', url: 'http://bandsintown.com/J.Cole' },
  { level: 2, name: 'J. Stalin', url: 'http://bandsintown.com/J.Stalin' },
  { level: 2, name: 'J. Valentine', url: 'http://bandsintown.com/J.Valentine' },
  { level: 2, name: 'J.R. Writer', url: 'http://bandsintown.com/J.R.Writer' },
  { level: 2, name: 'Ja Rule', url: 'http://bandsintown.com/JaRule' },
  { level: 2, name: 'Jack Parow', url: 'http://bandsintown.com/JackParow' },
  { level: 2, name: 'The Jacka', url: 'http://bandsintown.com/TheJacka' },
  {
    level: 2,
    name: 'Jackie Hill-Perry',
    url: 'http://bandsintown.com/JackieHillPerry',
  },
  { level: 2, name: 'Jadakiss', url: 'http://bandsintown.com/Jadakiss' },
  { level: 2, name: 'Jae Millz', url: 'http://bandsintown.com/JaeMillz' },
  { level: 2, name: 'Jahlil Beats', url: 'http://bandsintown.com/JahlilBeats' },
  { level: 2, name: 'Jake Miller', url: 'http://bandsintown.com/JakeMiller' },
  { level: 2, name: 'Jake One', url: 'http://bandsintown.com/JakeOne' },
  {
    level: 2,
    name: 'Jam Master Jay',
    url: 'http://bandsintown.com/Jam-MasterJay',
  },
  { level: 2, name: 'Jamal', url: 'http://bandsintown.com/Jamal' },
  { level: 2, name: 'Jamie Foxx', url: 'http://bandsintown.com/JamieFoxx' },
  {
    level: 2,
    name: 'Jarren Benton',
    url: 'http://bandsintown.com/JarrenBenton',
  },
  {
    level: 2,
    name: 'Jay Electronica',
    url: 'http://bandsintown.com/JayElectronica',
  },
  { level: 2, name: 'Jay Park', url: 'http://bandsintown.com/JayPark' },
  { level: 2, name: 'Jay Rock', url: 'http://bandsintown.com/JayRock' },
  { level: 2, name: 'Jay Z[1]', url: 'http://bandsintown.com/JAY-Z' },
  { level: 2, name: 'Jayo Felony', url: 'http://bandsintown.com/JayoFelony' },
  { level: 2, name: 'Jazz Cartier', url: 'http://bandsintown.com/JazzCartier' },
  { level: 2, name: 'Jazze Pha', url: 'http://bandsintown.com/JazzePha' },
  { level: 2, name: 'Jean Grae', url: 'http://bandsintown.com/JeanGrae' },
  { level: 2, name: 'Jeremiah Jae', url: 'http://bandsintown.com/JeremiahJae' },
  { level: 2, name: 'Jeremih', url: 'http://bandsintown.com/Jeremih' },
  {
    level: 2,
    name: 'Jermaine Dupri',
    url: 'http://bandsintown.com/JermaineDupri',
  },
  {
    level: 2,
    name: 'Jeru the Damaja',
    url: 'http://bandsintown.com/JerutheDamaja',
  },
  { level: 2, name: 'Jewell', url: 'http://bandsintown.com/Jewell' },
  { level: 2, name: 'Jibbs', url: 'http://bandsintown.com/Jibbs' },
  { level: 2, name: 'Jim Jones', url: 'http://bandsintown.com/JimJones' },
  { level: 2, name: 'Jme', url: 'http://bandsintown.com/JME' },
  { level: 2, name: 'Joe Budden', url: 'http://bandsintown.com/JoeBudden' },
  { level: 2, name: 'Joell Ortiz', url: 'http://bandsintown.com/JoellOrtiz' },
  { level: 2, name: 'Joey Badass', url: 'http://bandsintown.com/JoeyBadass' },
  { level: 2, name: 'John Cena', url: 'http://bandsintown.com/JohnCena' },
  { level: 2, name: 'Jon Connor', url: 'http://bandsintown.com/JonConnor' },
  { level: 2, name: 'Joyner Lucas', url: 'http://bandsintown.com/JoynerLucas' },
  { level: 2, name: 'JT Money', url: 'http://bandsintown.com/JTMoney' },
  {
    level: 2,
    name: 'JT the Bigga Figga',
    url: 'http://bandsintown.com/JTtheBiggaFigga',
  },
  {
    level: 2,
    name: 'Juelz Santana',
    url: 'http://bandsintown.com/JuelzSantana',
  },
  { level: 2, name: 'Juicy J', url: 'http://bandsintown.com/JuicyJ' },
  { level: 2, name: 'Jus Allah', url: 'http://bandsintown.com/JusAllah' },
  { level: 2, name: 'Just Ice', url: 'http://bandsintown.com/Just-Ice' },
  { level: 2, name: 'Juvenile', url: 'http://bandsintown.com/Juvenile' },
  { level: 2, name: 'K Camp', url: 'http://bandsintown.com/KCamp' },
  { level: 2, name: "K'naan", url: "http://bandsintown.com/K'naan" },
  { level: 2, name: 'K-OS', url: 'http://bandsintown.com/k-os' },
  { level: 2, name: 'K7', url: 'http://bandsintown.com/K7' },
  { level: 2, name: 'Kafani', url: 'http://bandsintown.com/Kafani' },
  { level: 2, name: 'Kam', url: 'http://bandsintown.com/Kam' },
  { level: 2, name: 'Kanye West[1]', url: 'http://bandsintown.com/KanyeWest' },
  { level: 2, name: 'Kap G', url: 'http://bandsintown.com/KAPG' },
  {
    level: 2,
    name: 'Kardinal Offishall',
    url: 'http://bandsintown.com/KardinalOffishall',
  },
  { level: 2, name: 'Kat Dahlia', url: 'http://bandsintown.com/KatDahlia' },
  {
    level: 2,
    name: 'Katie Got Bandz',
    url: 'http://bandsintown.com/KatieGotBandz',
  },
  { level: 2, name: 'KB', url: 'http://bandsintown.com/Kb' },
  {
    level: 2,
    name: 'Keak da Sneak',
    url: 'http://bandsintown.com/KeakdaSneak',
  },
  { level: 2, name: 'Keith Murray', url: 'http://bandsintown.com/KeithMurray' },
  {
    level: 2,
    name: 'Kendrick Lamar',
    url: 'http://bandsintown.com/KendrickLamar',
  },
  { level: 2, name: 'Kent Jones', url: 'http://bandsintown.com/KentJones' },
  { level: 2, name: 'Kerser', url: 'http://bandsintown.com/Kerser' },
  { level: 2, name: 'Kevin Gates', url: 'http://bandsintown.com/KevinGates' },
  { level: 2, name: 'Kevin McCall', url: 'http://bandsintown.com/KevinMcCall' },
  { level: 2, name: 'Khia', url: 'http://bandsintown.com/Khia' },
  { level: 2, name: 'Khleo', url: 'http://bandsintown.com/KhleoThomas' },
  { level: 2, name: 'Kia Shine', url: 'http://bandsintown.com/KiaShine' },
  { level: 2, name: 'Kid Capri', url: 'http://bandsintown.com/KidCapri' },
  { level: 2, name: 'Kid Cudi', url: 'http://bandsintown.com/KidCudi' },
  { level: 2, name: 'Kid Frost', url: 'http://bandsintown.com/KidFrost' },
  { level: 2, name: 'Kid Ink', url: 'http://bandsintown.com/KidInk' },
  { level: 2, name: 'Kid Rock', url: 'http://bandsintown.com/KidRock' },
  { level: 2, name: 'Kid Sister', url: 'http://bandsintown.com/KidSister' },
  { level: 2, name: 'Kidd Kidd', url: 'http://bandsintown.com/KiddKidd' },
  {
    level: 2,
    name: 'Killah Priest',
    url: 'http://bandsintown.com/KillahPriest',
  },
  { level: 2, name: 'Killer Mike', url: 'http://bandsintown.com/KillerMike' },
  { level: 2, name: 'Kilo Ali', url: 'http://bandsintown.com/KiloAli' },
  { level: 2, name: 'King Chip', url: 'http://bandsintown.com/KingChip' },
  { level: 2, name: 'King Gordy', url: 'http://bandsintown.com/KingGordy' },
  { level: 2, name: 'King L', url: 'http://bandsintown.com/KingL' },
  { level: 2, name: 'King Tee', url: 'http://bandsintown.com/KingTee' },
  { level: 2, name: 'Kirk Knight', url: 'http://bandsintown.com/KirkKnight' },
  { level: 2, name: 'Kirko Bangz', url: 'http://bandsintown.com/KirkoBangz' },
  { level: 2, name: 'Kitty', url: 'http://bandsintown.com/Kitty' },
  { level: 2, name: 'KJ-52', url: 'http://bandsintown.com/KJ-52' },
  {
    level: 2,
    name: "Knoc-turn'al",
    url: "http://bandsintown.com/Knoc-Turn'Al",
  },
  { level: 2, name: 'KO', url: 'http://bandsintown.com/KO' },
  { level: 2, name: 'Kodak Black', url: 'http://bandsintown.com/KodakBlack' },
  { level: 2, name: 'Kokane', url: 'http://bandsintown.com/Kokane' },
  { level: 2, name: 'Kool A.D', url: 'http://bandsintown.com/KoolA.D.' },
  { level: 2, name: 'Kool G Rap', url: 'http://bandsintown.com/KoolGRap' },
  { level: 2, name: 'Kool Keith', url: 'http://bandsintown.com/KoolKeith' },
  { level: 2, name: 'Kool Moe Dee', url: 'http://bandsintown.com/KoolMoeDee' },
  { level: 2, name: 'Krayzie Bone', url: 'http://bandsintown.com/KrayzieBone' },
  { level: 2, name: 'Kreayshawn', url: 'http://bandsintown.com/Kreayshawn' },
  { level: 2, name: 'Krizz Kaliko', url: 'http://bandsintown.com/KrizzKaliko' },
  { level: 2, name: 'KRS-One', url: 'http://bandsintown.com/KRS-One' },
  {
    level: 2,
    name: 'Kung Fu Vampire',
    url: 'http://bandsintown.com/KungFuVampire',
  },
  { level: 2, name: 'Kurious', url: 'http://bandsintown.com/Kurious' },
  { level: 2, name: 'Kurtis Blow', url: 'http://bandsintown.com/KurtisBlow' },
  { level: 2, name: 'Kurupt', url: 'http://bandsintown.com/Kurupt' },
  { level: 2, name: 'Kutt Calhoun', url: 'http://bandsintown.com/KuttCalhoun' },
  { level: 2, name: 'Kwamé', url: 'http://bandsintown.com/Kwamé' },
  { level: 2, name: 'Kyle', url: 'http://bandsintown.com/Kyle' },
  { level: 2, name: 'La Chat', url: 'http://bandsintown.com/LaChat' },
  {
    level: 2,
    name: 'La the Darkman',
    url: 'http://bandsintown.com/LatheDarkman',
  },
  { level: 2, name: 'Lady Luck', url: 'http://bandsintown.com/LadyLuck' },
  {
    level: 2,
    name: 'The Lady of Rage',
    url: 'http://bandsintown.com/TheLadyofRage',
  },
  { level: 2, name: 'Lakutis', url: 'http://bandsintown.com/Lakutis' },
  {
    level: 2,
    name: 'Large Professor',
    url: 'http://bandsintown.com/LargeProfessor',
  },
  { level: 2, name: 'Lauryn Hill', url: 'http://bandsintown.com/LaurenHill' },
  { level: 2, name: 'Lazarus', url: 'http://bandsintown.com/Lazarus' },
  { level: 2, name: 'Lecrae', url: 'http://bandsintown.com/Lecrae' },
  { level: 2, name: 'Left Brain', url: 'http://bandsintown.com/LeftBrain' },
  { level: 2, name: 'Lex Luger', url: 'http://bandsintown.com/LexLuger' },
  { level: 2, name: 'Lil Bibby', url: 'http://bandsintown.com/LilBibby' },
  { level: 2, name: 'Lil B', url: 'http://bandsintown.com/LilB' },
  { level: 2, name: 'Lil Debbie', url: 'http://bandsintown.com/LILDEBBIE' },
  { level: 2, name: 'Lil Dicky', url: 'http://bandsintown.com/LilDicky' },
  { level: 2, name: 'Lil Durk', url: 'http://bandsintown.com/LilDurk' },
  { level: 2, name: 'Lil Eazy-E', url: 'http://bandsintown.com/LilEazy-E' },
  { level: 2, name: 'Lil Herb', url: 'http://bandsintown.com/lilherb' },
  { level: 2, name: 'Lil Jon[1]', url: 'http://bandsintown.com/LilJon' },
  { level: 2, name: 'Lil Flip', url: 'http://bandsintown.com/LilFlip' },
  { level: 2, name: 'Lil Mama', url: "http://bandsintown.com/Lil'Mama" },
  { level: 2, name: 'Lil Reese', url: 'http://bandsintown.com/LilReese' },
  { level: 2, name: 'Lil Ru', url: 'http://bandsintown.com/LilRu' },
  { level: 2, name: 'Lil Scrappy', url: 'http://bandsintown.com/LilScrappy' },
  { level: 2, name: 'Lil Twist', url: 'http://bandsintown.com/LilTwist' },
  { level: 2, name: 'Lil Uzi Vert', url: 'http://bandsintown.com/LilUziVert' },
  { level: 2, name: 'Lil Wayne[1]', url: 'http://bandsintown.com/LilWayne' },
  { level: 2, name: 'Lil Wyte', url: 'http://bandsintown.com/LilWyte' },
  { level: 2, name: 'Lil Yachty', url: 'http://bandsintown.com/LilYachty' },
  { level: 2, name: 'Lil Zane', url: 'http://bandsintown.com/LilZane' },
  { level: 2, name: "Lil' Cease", url: "http://bandsintown.com/Lil'Cease" },
  { level: 2, name: "Lil' Fizz", url: 'http://bandsintown.com/LILFIZZ' },
  { level: 2, name: "Lil' Flip", url: 'http://bandsintown.com/LilFlip' },
  { level: 2, name: "Lil' Keke", url: 'http://bandsintown.com/LilKeke' },
  { level: 2, name: "Lil' Kim[2]", url: "http://bandsintown.com/Lil'Kim" },
  { level: 2, name: "Lil' O", url: "http://bandsintown.com/Lil'O" },
  { level: 2, name: "Lil' Troy", url: "http://bandsintown.com/Lil'Troy" },
  { level: 2, name: "Lil' Wil", url: 'http://bandsintown.com/LilWil' },
  { level: 2, name: 'LL Cool J[1]', url: 'http://bandsintown.com/LLCoolJ' },
  { level: 2, name: 'Lloyd Banks', url: 'http://bandsintown.com/LloydBanks' },
  { level: 2, name: 'Locksmith', url: 'http://bandsintown.com/LockSmith' },
  { level: 2, name: 'Logic', url: 'http://bandsintown.com/Logic' },
  { level: 2, name: 'LoLa Monroe', url: 'http://bandsintown.com/LolaMonroe' },
  { level: 2, name: 'Loon', url: 'http://bandsintown.com/Loon' },
  { level: 2, name: 'Lord Finesse', url: 'http://bandsintown.com/LordFinesse' },
  {
    level: 2,
    name: 'Lord Infamous',
    url: 'http://bandsintown.com/LordInfamous',
  },
  { level: 2, name: 'Los', url: 'http://bandsintown.com/Los' },
  { level: 2, name: 'Louis Logic', url: 'http://bandsintown.com/LouisLogic' },
  { level: 2, name: 'LoveRance', url: 'http://bandsintown.com/LoveRance' },
  { level: 2, name: 'Lowkey', url: 'http://bandsintown.com/Lowkey' },
  { level: 2, name: 'Ludacris[1]', url: 'http://bandsintown.com/Ludacris' },
  { level: 2, name: 'Luni Coleone', url: 'http://bandsintown.com/LuniColeone' },
  {
    level: 2,
    name: 'Lupe Fiasco[1]',
    url: 'http://bandsintown.com/LupeFiasco',
  },
  { level: 2, name: 'M-1', url: 'http://bandsintown.com/M-1' },
  { level: 2, name: 'M.I.A.', url: 'http://bandsintown.com/M.I.A.' },
  { level: 2, name: 'Mac', url: 'http://bandsintown.com/Mac' },
  { level: 2, name: 'Mac Dre', url: 'http://bandsintown.com/MacDre' },
  { level: 2, name: 'Mac Lethal', url: 'http://bandsintown.com/MacLethal' },
  { level: 2, name: 'Mac Mall', url: 'http://bandsintown.com/MacMall' },
  { level: 2, name: 'Mac Miller', url: 'http://bandsintown.com/MACMILLER' },
  {
    level: 2,
    name: 'Machine Gun Kelly',
    url: 'http://bandsintown.com/MachineGunKelly',
  },
  { level: 2, name: 'Mack 10', url: 'http://bandsintown.com/Mack10' },
  { level: 2, name: 'Mack Maine', url: 'http://bandsintown.com/MackMaine' },
  {
    level: 2,
    name: 'Macklemore',
    url: 'http://bandsintown.com/MacklemoreAndRyanLewis',
  },
  { level: 2, name: 'Mad Lion', url: 'http://bandsintown.com/MadLion' },
  { level: 2, name: 'Madchild', url: 'http://bandsintown.com/Madchild' },
  { level: 2, name: 'Madlib', url: 'http://bandsintown.com/Madlib' },
  { level: 2, name: 'Maejor Ali', url: 'http://bandsintown.com/MaejorAli' },
  { level: 2, name: 'Magic', url: 'http://bandsintown.com/Magic!' },
  { level: 2, name: 'Maino', url: 'http://bandsintown.com/Maino' },
  { level: 2, name: 'Mann', url: 'http://bandsintown.com/Mann' },
  { level: 2, name: 'Mannie Fresh', url: 'http://bandsintown.com/MannieFresh' },
  { level: 2, name: 'Marčelo', url: 'http://bandsintown.com/Marcelo' },
  { level: 2, name: 'Mark Battles', url: 'http://bandsintown.com/MarkBattles' },
  { level: 2, name: 'Marley Marl', url: 'http://bandsintown.com/MarleyMarl' },
  { level: 2, name: 'Marz', url: 'http://bandsintown.com/Marz' },
  { level: 2, name: 'Mase', url: 'http://bandsintown.com/Mase' },
  {
    level: 2,
    name: 'Masspike Miles',
    url: 'http://bandsintown.com/MASSPIKEMILES',
  },
  { level: 2, name: 'Masta Ace', url: 'http://bandsintown.com/MastaAce' },
  { level: 2, name: 'Masta Killa', url: 'http://bandsintown.com/MastaKilla' },
  { level: 2, name: 'Master P[1]', url: 'http://bandsintown.com/MasterP' },
  { level: 2, name: 'Matt Toka', url: 'http://bandsintown.com/MattToka' },
  { level: 2, name: 'Max B', url: 'http://bandsintown.com/MaxB' },
  { level: 2, name: 'MC Breed', url: 'http://bandsintown.com/MCBreed' },
  { level: 2, name: 'MC Eiht', url: 'http://bandsintown.com/MCEiht' },
  { level: 2, name: 'MC Frontalot', url: 'http://bandsintown.com/MCFrontalot' },
  { level: 2, name: 'MC Hammer[1]', url: 'http://bandsintown.com/MCHammer' },
  { level: 2, name: 'MC Jin', url: 'http://bandsintown.com/MCJin' },
  { level: 2, name: 'MC Lyte', url: 'http://bandsintown.com/MCLyte' },
  { level: 2, name: 'MC Mong', url: 'http://bandsintown.com/MCMong' },
  { level: 2, name: 'MC Ren', url: 'http://bandsintown.com/MCRen' },
  { level: 2, name: 'MC Serch', url: 'http://bandsintown.com/MCSerch' },
  { level: 2, name: 'MC Shan', url: 'http://bandsintown.com/MCShan' },
  { level: 2, name: 'MC Solaar', url: 'http://bandsintown.com/MCSolaar' },
  { level: 2, name: 'Meek Mill', url: 'http://bandsintown.com/MeekMill' },
  { level: 2, name: 'Melle Mel', url: 'http://bandsintown.com/MelleMel' },
  {
    level: 2,
    name: 'Mellow Man Ace',
    url: 'http://bandsintown.com/MellowManAce',
  },
  {
    level: 2,
    name: 'Memphis Bleek',
    url: 'http://bandsintown.com/MemphisBleek',
  },
  { level: 2, name: 'Messy Marv', url: 'http://bandsintown.com/MessyMarv' },
  { level: 2, name: 'Method Man', url: 'http://bandsintown.com/MethodMan' },
  { level: 2, name: 'Metro Boomin', url: 'http://bandsintown.com/MetroBoomin' },
  { level: 2, name: 'MF Doom', url: 'http://bandsintown.com/MFDoom' },
  { level: 2, name: 'MF Grimm', url: 'http://bandsintown.com/MFGrimm' },
  { level: 2, name: 'Mia X', url: 'http://bandsintown.com/MiaX' },
  { level: 2, name: 'Mic Geronimo', url: 'http://bandsintown.com/MicGeronimo' },
  { level: 2, name: 'Mick Jenkins', url: 'http://bandsintown.com/MickJenkins' },
  { level: 2, name: 'Mickey Factz', url: 'http://bandsintown.com/MickeyFactz' },
  { level: 2, name: 'Mike Dean', url: 'http://bandsintown.com/MikeDean' },
  { level: 2, name: 'Mike G', url: 'http://bandsintown.com/MikeG' },
  { level: 2, name: 'Mike Jones', url: 'http://bandsintown.com/MikeJones' },
  { level: 2, name: 'Mike Posner', url: 'http://bandsintown.com/MikePosner' },
  { level: 2, name: 'Mike Stud', url: 'http://bandsintown.com/MikeStud' },
  {
    level: 2,
    name: 'Mike Will Made It',
    url: 'http://bandsintown.com/MikeWiLLMadeIt',
  },
  { level: 2, name: 'Mike Zombie', url: 'http://bandsintown.com/MikeZombie' },
  { level: 2, name: 'Milo', url: 'http://bandsintown.com/Milo' },
  { level: 2, name: 'Mims[1]', url: 'http://bandsintown.com/Mims' },
  { level: 2, name: 'Mino', url: 'http://bandsintown.com/Mino' },
  {
    level: 2,
    name: 'Missy Elliott[1]',
    url: 'http://bandsintown.com/MissyElliott',
  },
  {
    level: 2,
    name: 'Mistah F.A.B.',
    url: 'http://bandsintown.com/MistahF.A.B.',
  },
  { level: 2, name: 'Mitchy Slick', url: 'http://bandsintown.com/MitchySlick' },
  { level: 2, name: 'Mod Sun', url: 'http://bandsintown.com/ModSun' },
  { level: 2, name: 'Monie Love', url: 'http://bandsintown.com/MonieLove' },
  { level: 2, name: 'Mos Def[2]', url: 'http://bandsintown.com/MosDef' },
  { level: 2, name: 'Mr. Capone-E', url: 'http://bandsintown.com/Mr.Capone-E' },
  { level: 2, name: 'Mr. Cheeks', url: 'http://bandsintown.com/Mr.Cheeks' },
  {
    level: 2,
    name: 'Mr. Collipark',
    url: 'http://bandsintown.com/Mr.Collipark',
  },
  { level: 2, name: 'Mr. Criminal', url: 'http://bandsintown.com/MrCriminal' },
  { level: 2, name: 'Mr. Lif', url: 'http://bandsintown.com/Mr.Lif' },
  {
    level: 2,
    name: "Mr. Muthafuckin' eXquire",
    url: "http://bandsintown.com/Mr.Muthafuckin'eXquire",
  },
  { level: 2, name: 'Mr. Porter', url: 'http://bandsintown.com/Mr.Porter' },
  { level: 2, name: 'Ms. Jade', url: 'http://bandsintown.com/Ms.Jade' },
  { level: 2, name: 'Murphy Lee', url: 'http://bandsintown.com/MurphyLee' },
  { level: 2, name: 'Murs', url: 'http://bandsintown.com/Murs' },
  { level: 2, name: 'Mystikal', url: 'http://bandsintown.com/Mystikal' },
  { level: 2, name: 'N.O.R.E.', url: 'http://bandsintown.com/N.O.R.E' },
  { level: 2, name: 'Napoleon', url: 'http://bandsintown.com/Napoleon' },
  { level: 2, name: 'Nas[1]', url: 'http://bandsintown.com/Nas' },
  { level: 2, name: 'Nature', url: 'http://bandsintown.com/Nature' },
  { level: 2, name: 'Nav', url: 'http://bandsintown.com/Nav' },
  { level: 2, name: 'Nebu Kiniza', url: 'http://bandsintown.com/NebuKiniza' },
  { level: 2, name: 'Necro', url: 'http://bandsintown.com/Necro' },
  { level: 2, name: 'Needlz', url: 'http://bandsintown.com/Needlz' },
  { level: 2, name: 'Nelly', url: 'http://bandsintown.com/Nelly' },
  { level: 2, name: 'NF', url: 'http://bandsintown.com/NF' },
  { level: 2, name: 'Nick Cannon', url: 'http://bandsintown.com/NickCannon' },
  {
    level: 2,
    name: 'Nicki Minaj[1]',
    url: 'http://bandsintown.com/NickiMinaj',
  },
  { level: 2, name: 'Nicky da B', url: 'http://bandsintown.com/NickyDaB' },
  { level: 2, name: 'Nicole Wray', url: 'http://bandsintown.com/NicoleWray' },
  {
    level: 2,
    name: 'Nipsey Hussle',
    url: 'http://bandsintown.com/NipseyHussle',
  },
  { level: 2, name: 'Nitty', url: 'http://bandsintown.com/Nitty' },
  {
    level: 2,
    name: "Nitty Scott', MC",
    url: "http://bandsintown.com/NittyScott',MC",
  },
  { level: 2, name: 'NoClue', url: 'http://bandsintown.com/NoClue' },
  { level: 2, name: 'No Malice', url: 'http://bandsintown.com/NoMalice' },
  {
    level: 2,
    name: 'Noah "40" Shebib',
    url: 'http://bandsintown.com/Noah40Shebib',
  },
  { level: 2, name: 'Noname', url: 'http://bandsintown.com/Noname' },
  { level: 2, name: 'Nonchalant', url: 'http://bandsintown.com/Nonchalant' },
  { level: 2, name: 'Nottz', url: 'http://bandsintown.com/Nottz' },
  { level: 2, name: 'Nujabes', url: 'http://bandsintown.com/Nujabes' },
  { level: 2, name: 'Numskull', url: 'http://bandsintown.com/Numbskull' },
  { level: 2, name: 'Nyzzy Nyce', url: 'http://bandsintown.com/NyzzyNyce' },
  { level: 2, name: 'Obie Trice', url: 'http://bandsintown.com/ObieTrice' },
  { level: 2, name: 'Oddisee', url: 'http://bandsintown.com/Oddisee' },
  { level: 2, name: 'OG Maco', url: 'http://bandsintown.com/OGMACO' },
  { level: 2, name: 'Oh No', url: 'http://bandsintown.com/OhNo' },
  {
    level: 2,
    name: 'OJ da Juiceman',
    url: 'http://bandsintown.com/OJdaJuiceman',
  },
  {
    level: 2,
    name: "Ol' Dirty Bastard",
    url: "http://bandsintown.com/Ol'DirtyBastard",
  },
  { level: 2, name: 'Olamide', url: 'http://bandsintown.com/Olamide' },
  { level: 2, name: 'Olivia', url: 'http://bandsintown.com/Olivia' },
  { level: 2, name: 'Omarion', url: 'http://bandsintown.com/Omarion' },
  {
    level: 2,
    name: 'Open Mike Eagle',
    url: 'http://bandsintown.com/OpenMikeEagle',
  },
  { level: 2, name: 'P. Reign', url: 'http://bandsintown.com/PREIGN' },
  { level: 2, name: 'P.C.T', url: 'http://bandsintown.com/P.C.T' },
  { level: 2, name: 'Papoose', url: 'http://bandsintown.com/Papoose' },
  { level: 2, name: 'Paris', url: 'http://bandsintown.com/Paris' },
  {
    level: 2,
    name: 'PARTYNEXTDOOR',
    url: 'http://bandsintown.com/PARTYNEXTDOOR',
  },
  { level: 2, name: 'Pastor Troy', url: 'http://bandsintown.com/PastorTroy' },
  { level: 2, name: 'Paul Wall', url: 'http://bandsintown.com/PaulWall' },
  { level: 2, name: 'Peedi Peedi', url: 'http://bandsintown.com/PeediPeedi' },
  {
    level: 2,
    name: 'Peewee Longway',
    url: 'http://bandsintown.com/PeeWeeLongway',
  },
  { level: 2, name: 'Pacewon', url: 'http://bandsintown.com/Pacewon' },
  { level: 2, name: 'Percee P', url: 'http://bandsintown.com/PerceeP' },
  { level: 2, name: 'Petey Pablo', url: 'http://bandsintown.com/PeteyPablo' },
  {
    level: 2,
    name: 'Pharoahe Monch',
    url: 'http://bandsintown.com/PharoaheMonch',
  },
  {
    level: 2,
    name: 'Pharrell Williams',
    url: 'http://bandsintown.com/PharrellWilliams',
  },
  { level: 2, name: 'Phat Kat', url: 'http://bandsintown.com/PhatKat' },
  { level: 2, name: 'Philthy Rich', url: 'http://bandsintown.com/PhilthyRich' },
  { level: 2, name: 'Phyno', url: 'http://bandsintown.com/Phyno' },
  { level: 2, name: 'Pill', url: 'http://bandsintown.com/Pill' },
  { level: 2, name: 'Pimp C', url: 'http://bandsintown.com/PimpC' },
  { level: 2, name: 'Pitbull[1]', url: 'http://bandsintown.com/Pitbull' },
  { level: 2, name: 'Planet Asia', url: 'http://bandsintown.com/PlanetAsia' },
  { level: 2, name: 'Planetary', url: 'http://bandsintown.com/Planetary' },
  { level: 2, name: 'Plies', url: 'http://bandsintown.com/Plies' },
  {
    level: 2,
    name: 'Playboi Carti',
    url: 'http://bandsintown.com/PlayboiCarti',
  },
  { level: 2, name: 'PNC', url: 'http://bandsintown.com/PNC' },
  { level: 2, name: 'Porta', url: 'http://bandsintown.com/Porta' },
  { level: 2, name: 'Positive K', url: 'http://bandsintown.com/PositiveK' },
  { level: 2, name: 'Post Malone', url: 'http://bandsintown.com/PostMalone' },
  { level: 2, name: 'Pras', url: 'http://bandsintown.com/Pras' },
  { level: 2, name: 'Prince Paul', url: 'http://bandsintown.com/PrincePaul' },
  { level: 2, name: 'Prodigy', url: 'http://bandsintown.com/Prodigy' },
  {
    level: 2,
    name: 'Professor Green',
    url: 'http://bandsintown.com/ProfessorGreen',
  },
  { level: 2, name: 'Project Pat', url: 'http://bandsintown.com/ProjectPat' },
  { level: 2, name: 'Proof', url: 'http://bandsintown.com/Proof' },
  { level: 2, name: 'Prozak', url: 'http://bandsintown.com/Prozak' },
  { level: 2, name: 'Psy', url: 'http://bandsintown.com/Psy' },
  { level: 2, name: 'Pusha T', url: 'http://bandsintown.com/PushaT' },
  { level: 2, name: 'Q-Tip', url: 'http://bandsintown.com/Q-Tip' },
  { level: 2, name: 'Quavo', url: 'http://bandsintown.com/Quavo' },
  {
    level: 2,
    name: 'Queen Latifah',
    url: 'http://bandsintown.com/QueenLatifah',
  },
  { level: 2, name: 'Queen Pen', url: 'http://bandsintown.com/QueenPen' },
  { level: 2, name: 'The Quiett', url: 'http://bandsintown.com/TheQuiett' },
  { level: 2, name: 'Qwazaar', url: 'http://bandsintown.com/Qwazaar' },
  { level: 2, name: 'Qwel', url: 'http://bandsintown.com/Qwel' },
  { level: 2, name: 'R. Kelly', url: 'http://bandsintown.com/R.Kelly' },
  {
    level: 2,
    name: 'R.A. the Rugged Man',
    url: 'http://bandsintown.com/R.A.TheRuggedMan',
  },
  { level: 2, name: 'Raekwon', url: 'http://bandsintown.com/Raekwon' },
  { level: 2, name: 'Rah Digga', url: 'http://bandsintown.com/RahDigga' },
  { level: 2, name: 'Rahzel', url: 'http://bandsintown.com/Rahzel' },
  { level: 2, name: 'Rakim', url: 'http://bandsintown.com/Rakim' },
  { level: 2, name: 'Rampage', url: 'http://bandsintown.com/Rampage' },
  { level: 2, name: 'Rap Monster', url: 'http://bandsintown.com/RapMonster' },
  {
    level: 2,
    name: "Rappin' 4-Tay",
    url: "http://bandsintown.com/Rappin'4-Tay",
  },
  { level: 2, name: 'Rapsody', url: 'http://bandsintown.com/Rapsody' },
  { level: 2, name: 'Ras Kass', url: 'http://bandsintown.com/RasKass' },
  { level: 2, name: 'Rasheeda', url: 'http://bandsintown.com/Rasheeda' },
  { level: 2, name: 'Ravi', url: 'http://bandsintown.com/Ravi' },
  { level: 2, name: 'Ray Cash', url: 'http://bandsintown.com/RayCash' },
  { level: 2, name: 'Ray J', url: 'http://bandsintown.com/RayJ' },
  { level: 2, name: 'Raz Fresco', url: 'http://bandsintown.com/razfresco' },
  { level: 2, name: 'RBX', url: 'http://bandsintown.com/RBX' },
  { level: 2, name: 'Really Doe', url: 'http://bandsintown.com/ReallyDoe' },
  { level: 2, name: 'Red Café', url: 'http://bandsintown.com/RedCafe' },
  { level: 2, name: 'Redfoo', url: 'http://bandsintown.com/Redfoo' },
  { level: 2, name: 'Redman', url: 'http://bandsintown.com/Redman' },
  {
    level: 2,
    name: 'Reef the Lost Cauze',
    url: 'http://bandsintown.com/ReeftheLostCauze',
  },
  { level: 2, name: 'Reema Major', url: 'http://bandsintown.com/ReemaMajor' },
  { level: 2, name: 'Reks', url: 'http://bandsintown.com/Reks' },
  { level: 2, name: 'Remy Ma', url: 'http://bandsintown.com/RemyMa' },
  { level: 2, name: 'Rhymefest', url: 'http://bandsintown.com/Rhymefest' },
  { level: 2, name: 'Rich Boy', url: 'http://bandsintown.com/RichBoy' },
  { level: 2, name: 'Rich Chigga', url: 'http://bandsintown.com/RichChigga' },
  {
    level: 2,
    name: 'Rich Homie Quan',
    url: 'http://bandsintown.com/RichHomieQuan',
  },
  { level: 2, name: 'Rich The Kid', url: 'http://bandsintown.com/richthekid' },
  { level: 2, name: 'Richie Rich', url: 'http://bandsintown.com/RichieRich' },
  { level: 2, name: 'Rick Ross[1]', url: 'http://bandsintown.com/RickRoss' },
  { level: 2, name: 'Rico Love', url: 'http://bandsintown.com/RicoLove' },
  { level: 2, name: 'Riff Raff', url: 'http://bandsintown.com/RiFFRAFF' },
  { level: 2, name: 'Rittz', url: 'http://bandsintown.com/Rittz' },
  { level: 2, name: 'RJ', url: 'http://bandsintown.com/RJ' },
  { level: 2, name: 'RJD2', url: 'http://bandsintown.com/RJD2' },
  { level: 2, name: 'Rob Sonic', url: 'http://bandsintown.com/RobSonic' },
  { level: 2, name: 'Rob Stone', url: 'http://bandsintown.com/RobStone' },
  { level: 2, name: 'Roc Marciano', url: 'http://bandsintown.com/RocMarciano' },
  { level: 2, name: 'Rockie Fresh', url: 'http://bandsintown.com/RockieFresh' },
  { level: 2, name: 'Rocko', url: 'http://bandsintown.com/Rocko' },
  {
    level: 2,
    name: 'Roger Troutman',
    url: 'http://bandsintown.com/RogerTroutman',
  },
  { level: 2, name: 'Romeo Miller', url: 'http://bandsintown.com/RomeoMiller' },
  { level: 2, name: 'Ronnie Radke', url: 'http://bandsintown.com/RonnieRadke' },
  { level: 2, name: 'Roots Manuva', url: 'http://bandsintown.com/RootsManuva' },
  { level: 2, name: 'Roscoe', url: 'http://bandsintown.com/Roscoe' },
  { level: 2, name: 'Roscoe Dash', url: 'http://bandsintown.com/RoscoeDash' },
  { level: 2, name: 'Rowdy Rebel', url: 'http://bandsintown.com/RowdyRebel' },
  {
    level: 2,
    name: 'Roxanne Shanté',
    url: 'http://bandsintown.com/RoxanneShanté',
  },
  { level: 2, name: 'Royce da 5\'9"', url: 'http://bandsintown.com/RoyceDa59' },
  { level: 2, name: 'Russ', url: 'http://bandsintown.com/Russ' },
  {
    level: 2,
    name: 'Rucka Rucka Ali',
    url: 'http://bandsintown.com/RuckaRuckaALI',
  },
  { level: 2, name: 'Rye Rye', url: 'http://bandsintown.com/RyeRye' },
  { level: 2, name: 'RZA', url: 'http://bandsintown.com/RZA' },
  { level: 2, name: 'Sadat X', url: 'http://bandsintown.com/SadatX' },
  { level: 2, name: 'Sadistik', url: 'http://bandsintown.com/Sadistik' },
  { level: 2, name: 'Sage Francis', url: 'http://bandsintown.com/SageFrancis' },
  {
    level: 2,
    name: 'Sage the Gemini',
    url: 'http://bandsintown.com/SageTheGemini',
  },
  { level: 2, name: 'Saigon', url: 'http://bandsintown.com/Saigon' },
  { level: 2, name: 'Sammy Adams', url: 'http://bandsintown.com/SammyAdams' },
  { level: 2, name: 'San E', url: 'http://bandsintown.com/SANE' },
  { level: 2, name: 'San Quinn', url: 'http://bandsintown.com/SanQuinn' },
  { level: 2, name: 'Sarkodie', url: 'http://bandsintown.com/Sarkodie' },
  { level: 2, name: 'Sauce Money', url: 'http://bandsintown.com/SauceMoney' },
  { level: 2, name: 'Savage', url: 'http://bandsintown.com/Savage' },
  { level: 2, name: 'Scarface[1]', url: 'http://bandsintown.com/Scarface' },
  { level: 2, name: 'Schoolboy Q', url: 'http://bandsintown.com/SchoolBoyQ' },
  { level: 2, name: 'Schoolly D', url: 'http://bandsintown.com/SchoollyD' },
  { level: 2, name: 'Scott Storch', url: 'http://bandsintown.com/ScottStorch' },
  { level: 2, name: 'Scotty', url: 'http://bandsintown.com/Scotty' },
  { level: 2, name: 'Scribe', url: 'http://bandsintown.com/Scribe' },
  { level: 2, name: 'Scrufizzer', url: 'http://bandsintown.com/Scrufizzer' },
  { level: 2, name: 'Sean Combs[2]', url: 'http://bandsintown.com/SeanCombs' },
  { level: 2, name: 'Sean Paul', url: 'http://bandsintown.com/SeanPaul' },
  { level: 2, name: 'Sean Price', url: 'http://bandsintown.com/SeanPrice' },
  {
    level: 2,
    name: 'Shabazz the Disciple',
    url: 'http://bandsintown.com/ShabazztheDisciple',
  },
  { level: 2, name: 'Shad', url: 'http://bandsintown.com/Shad' },
  { level: 2, name: 'Shade Sheist', url: 'http://bandsintown.com/ShadeSheist' },
  { level: 2, name: 'Shady Nate', url: 'http://bandsintown.com/ShadyNate' },
  { level: 2, name: 'Shaggy', url: 'http://bandsintown.com/Shaggy' },
  {
    level: 2,
    name: 'Shaggy 2 Dope',
    url: 'http://bandsintown.com/Shaggy2Dope',
  },
  {
    level: 2,
    name: "Shaquille O'Neal",
    url: "http://bandsintown.com/ShaquilleO'Neal",
  },
  { level: 2, name: 'Shawnna', url: 'http://bandsintown.com/Shawnna' },
  { level: 2, name: 'Shawty Lo', url: 'http://bandsintown.com/ShawtyLo' },
  { level: 2, name: 'Sheek Louch', url: 'http://bandsintown.com/SheekLouch' },
  { level: 2, name: 'Shing02', url: 'http://bandsintown.com/Shing02' },
  { level: 2, name: 'Sho Baraka', url: 'http://bandsintown.com/ShoBaraka' },
  { level: 2, name: 'Shock G', url: 'http://bandsintown.com/Shock-G' },
  { level: 2, name: 'Shorty', url: 'http://bandsintown.com/Shorty' },
  { level: 2, name: 'Shwayze', url: 'http://bandsintown.com/Shwayze' },
  { level: 2, name: 'Shy Glizzy', url: 'http://bandsintown.com/ShyGlizzy' },
  { level: 2, name: 'Shyheim', url: 'http://bandsintown.com/Shyheim' },
  { level: 2, name: 'Shyne', url: 'http://bandsintown.com/Shyne' },
  { level: 2, name: 'Silentó', url: 'http://bandsintown.com/Silento' },
  {
    level: 2,
    name: 'Silkk the Shocker',
    url: 'http://bandsintown.com/SilkktheShocker',
  },
  { level: 2, name: 'Silla', url: 'http://bandsintown.com/Silla' },
  {
    level: 2,
    name: 'Sir Mix-a-Lot',
    url: 'http://bandsintown.com/SirMix-A-Lot',
  },
  { level: 2, name: 'Sirah', url: 'http://bandsintown.com/Sirah' },
  { level: 2, name: 'Skee-Lo', url: 'http://bandsintown.com/Skee-Lo' },
  { level: 2, name: 'Skeme', url: 'http://bandsintown.com/Skeme' },
  { level: 2, name: 'Skinnyman', url: 'http://bandsintown.com/Skinnyman' },
  { level: 2, name: 'Skyzoo', url: 'http://bandsintown.com/Skyzoo' },
  { level: 2, name: 'SL Jones', url: 'http://bandsintown.com/SLJones' },
  { level: 2, name: 'Sleepy Brown', url: 'http://bandsintown.com/SleepyBrown' },
  { level: 2, name: 'Slick Rick[2]', url: 'http://bandsintown.com/SlickRick' },
  { level: 2, name: 'Slim Thug', url: 'http://bandsintown.com/SlimThug' },
  { level: 2, name: 'Slug', url: 'http://bandsintown.com/Slug' },
  { level: 2, name: 'Smitty', url: 'http://bandsintown.com/Smitty' },
  { level: 2, name: 'Smoke DZA', url: 'http://bandsintown.com/SmokeDZA' },
  { level: 2, name: 'Smooth', url: 'http://bandsintown.com/Smooth' },
  {
    level: 2,
    name: 'Smoothe da Hustler',
    url: 'http://bandsintown.com/SmootheDaHustler',
  },
  { level: 2, name: 'Snoop Dogg[1]', url: 'http://bandsintown.com/SnoopDogg' },
  { level: 2, name: 'Snootie Wild', url: 'http://bandsintown.com/SnootieWILD' },
  {
    level: 2,
    name: 'Snow Tha Product',
    url: 'http://bandsintown.com/SnowThaProduct',
  },
  { level: 2, name: 'Sole', url: 'http://bandsintown.com/Sole' },
  {
    level: 2,
    name: 'Sonny Digital',
    url: 'http://bandsintown.com/SonnyDigital',
  },
  { level: 2, name: 'SonReal', url: 'http://bandsintown.com/SonReal' },
  {
    level: 2,
    name: 'Soopafly',
    url: 'http://bandsintown.com/Priest%22Soopafly%22Brooks',
  },
  {
    level: 2,
    name: 'Soulja Boy',
    url: "http://bandsintown.com/SouljaBoyTell'Em",
  },
  { level: 2, name: 'Soulja Slim', url: 'http://bandsintown.com/SouljaSlim' },
  {
    level: 2,
    name: 'South Park Mexican',
    url: 'http://bandsintown.com/SouthParkMexican',
  },
  { level: 2, name: 'Southside', url: 'http://bandsintown.com/Southside' },
  {
    level: 2,
    name: 'SpaceGhostPurrp',
    url: 'http://bandsintown.com/Spaceghostpurrp',
  },
  { level: 2, name: 'Special Ed', url: 'http://bandsintown.com/SpecialEd' },
  { level: 2, name: 'Spice 1', url: 'http://bandsintown.com/Spice1' },
  { level: 2, name: 'Spider Loc', url: 'http://bandsintown.com/SpiderLoc' },
  { level: 2, name: 'Spoonie Gee', url: 'http://bandsintown.com/SpoonieGee' },
  { level: 2, name: 'Spose', url: 'http://bandsintown.com/Spose' },
  { level: 2, name: 'Spot', url: 'http://bandsintown.com/Spot' },
  { level: 2, name: 'Stalley', url: 'http://bandsintown.com/Stalley' },
  { level: 2, name: 'Starlito', url: 'http://bandsintown.com/Starlito' },
  { level: 2, name: 'Stat Quo', url: 'http://bandsintown.com/StatQuo' },
  { level: 2, name: 'Static Major', url: 'http://bandsintown.com/StaticMajor' },
  {
    level: 2,
    name: 'Statik Selektah',
    url: 'http://bandsintown.com/StatikSelektah',
  },
  { level: 2, name: 'Steady B', url: 'http://bandsintown.com/DJSTEADYB.' },
  { level: 2, name: 'Stevie Joe', url: 'http://bandsintown.com/StevieJoe' },
  { level: 2, name: 'Stevie Stone', url: 'http://bandsintown.com/StevieStone' },
  {
    level: 2,
    name: 'Sticky Fingaz',
    url: 'http://bandsintown.com/StickyFingaz',
  },
  { level: 2, name: 'Stretch', url: 'http://bandsintown.com/Stretch' },
  { level: 2, name: 'Styles P', url: 'http://bandsintown.com/StylesP' },
  { level: 2, name: 'Substantial', url: 'http://bandsintown.com/Substantial' },
  { level: 2, name: 'Suga Free', url: 'http://bandsintown.com/SugaFree' },
  { level: 2, name: 'Swings', url: 'http://bandsintown.com/Swings' },
  { level: 2, name: 'Swizz Beatz', url: 'http://bandsintown.com/SwizzBeatz' },
  { level: 2, name: 'SwizZz', url: 'http://bandsintown.com/SwizZz' },
  { level: 2, name: 'Syd Tha Kyd', url: 'http://bandsintown.com/SydThaKyd' },
  { level: 2, name: 'SZA', url: 'http://bandsintown.com/SZA' },
  { level: 2, name: 'T-Bone', url: 'http://bandsintown.com/T-Bone' },
  { level: 2, name: 'T-Nutty', url: 'http://bandsintown.com/T-Nutty' },
  { level: 2, name: 'T-Pain', url: 'http://bandsintown.com/T-Pain' },
  { level: 2, name: 'T-Wayne', url: 'http://bandsintown.com/T-Wayne' },
  { level: 2, name: 'T.I.[1]', url: 'http://bandsintown.com/T.I.' },
  { level: 2, name: 'T.O.P', url: 'http://bandsintown.com/T.O.P' },
  { level: 2, name: 'Tabi Bonney', url: 'http://bandsintown.com/TabiBonney' },
  { level: 2, name: 'Tablo', url: 'http://bandsintown.com/Tablo' },
  { level: 2, name: 'Taio Cruz', url: 'http://bandsintown.com/TaioCruz' },
  { level: 2, name: 'Takeoff', url: 'http://bandsintown.com/TakeOff' },
  { level: 2, name: 'Talib Kweli', url: 'http://bandsintown.com/TalibKweli' },
  { level: 2, name: 'Tay Dizm', url: 'http://bandsintown.com/TayDizm' },
  { level: 2, name: 'Tay-K', url: 'http://bandsintown.com/Tay-K' },
  { level: 2, name: 'Teairra Marí', url: 'http://bandsintown.com/TeairraMari' },
  { level: 2, name: 'Tech N9ne', url: 'http://bandsintown.com/TechN9ne' },
  { level: 2, name: 'Tedashii', url: 'http://bandsintown.com/Tedashii' },
  { level: 2, name: 'TeeFlii', url: 'http://bandsintown.com/TeeFLii' },
  { level: 2, name: 'Tee Grizzley', url: 'http://bandsintown.com/Teegrizzley' },
  { level: 2, name: 'Tekitha', url: 'http://bandsintown.com/Tekitha' },
  { level: 2, name: 'Tela', url: 'http://bandsintown.com/Tela' },
  { level: 2, name: 'Termanology', url: 'http://bandsintown.com/Termanology' },
  {
    level: 2,
    name: 'Terrace Martin',
    url: 'http://bandsintown.com/TerraceMartin',
  },
  {
    level: 2,
    name: 'Teyana Taylor',
    url: 'http://bandsintown.com/TeyanaTaylor',
  },
  {
    level: 2,
    name: 'Tha Trademarc',
    url: 'http://bandsintown.com/ThaTrademarc',
  },
  { level: 2, name: 'The-Dream', url: 'http://bandsintown.com/The-Dream' },
  {
    level: 2,
    name: 'Theophilus London',
    url: 'http://bandsintown.com/TheophilusLondon',
  },
  { level: 2, name: 'Timaya', url: 'http://bandsintown.com/timaya' },
  { level: 2, name: 'Timbaland', url: 'http://bandsintown.com/Timbaland' },
  { level: 2, name: 'Tinie Tempah', url: 'http://bandsintown.com/TinieTempah' },
  { level: 2, name: 'Tink (musician)', url: 'http://bandsintown.com/Tink' },
  { level: 2, name: 'TobyMac', url: 'http://bandsintown.com/tobyMac' },
  { level: 2, name: 'Tonedeff', url: 'http://bandsintown.com/Tonedeff' },
  { level: 2, name: 'Tony Yayo', url: 'http://bandsintown.com/TonyYayo' },
  { level: 2, name: 'Too Short', url: 'http://bandsintown.com/Too$hort' },
  { level: 2, name: 'Torch (American)', url: 'http://bandsintown.com/Torch' },
  { level: 2, name: 'Tory Lanez', url: 'http://bandsintown.com/ToryLanez' },
  { level: 2, name: 'Tracey Lee', url: 'http://bandsintown.com/TraceyLee' },
  {
    level: 2,
    name: 'Trae tha Truth',
    url: 'http://bandsintown.com/TRAETHATRUTH',
  },
  {
    level: 2,
    name: 'Tragedy Khadafi',
    url: 'http://bandsintown.com/TragedyKhadafi',
  },
  { level: 2, name: 'Travis Scott', url: 'http://bandsintown.com/TravisScott' },
  {
    level: 2,
    name: 'Traxamillion',
    url: 'http://bandsintown.com/Traxamillion',
  },
  { level: 2, name: 'Tray Deee', url: 'http://bandsintown.com/TrayDee' },
  { level: 2, name: 'Treach', url: 'http://bandsintown.com/Treach' },
  { level: 2, name: 'Trey Songz', url: 'http://bandsintown.com/TreySongz' },
  { level: 2, name: 'Trick Daddy', url: 'http://bandsintown.com/TrickDaddy' },
  { level: 2, name: 'Trick-Trick', url: 'http://bandsintown.com/TrickTrick' },
  { level: 2, name: 'Trina', url: 'http://bandsintown.com/Trina' },
  {
    level: 2,
    name: 'Trinidad James',
    url: 'http://bandsintown.com/TrinidadJames',
  },
  { level: 2, name: 'Trip Lee', url: 'http://bandsintown.com/TripLee' },
  { level: 2, name: 'Troy Ave', url: 'http://bandsintown.com/troyave' },
  { level: 2, name: 'Turf Talk', url: 'http://bandsintown.com/TurfTalk' },
  { level: 2, name: 'Turk', url: 'http://bandsintown.com/Turk' },
  { level: 2, name: 'Twista', url: 'http://bandsintown.com/Twista' },
  {
    level: 2,
    name: 'Twisted Insane',
    url: 'http://bandsintown.com/TwistedInsane',
  },
  {
    level: 2,
    name: 'Ty Dolla Sign',
    url: 'http://bandsintown.com/TyDolla$ign',
  },
  { level: 2, name: 'Tyga', url: 'http://bandsintown.com/Tyga' },
  { level: 2, name: 'Tyler Joseph', url: 'http://bandsintown.com/tylerjoseph' },
  {
    level: 2,
    name: "Tyler', The Creator",
    url: "http://bandsintown.com/Tyler',TheCreator",
  },
  { level: 2, name: 'U-God', url: 'http://bandsintown.com/U-God' },
  { level: 2, name: 'Ugly God', url: 'http://bandsintown.com/UglyGod' },
  { level: 2, name: 'Uncle Murda', url: 'http://bandsintown.com/UncleMurda' },
  { level: 2, name: 'Unk', url: 'http://bandsintown.com/DJUnk' },
  { level: 2, name: 'U$O', url: 'http://bandsintown.com/U$O' },
  { level: 2, name: 'V-Nasty', url: 'http://bandsintown.com/V-Nasty' },
  { level: 2, name: 'V.I.C.', url: 'http://bandsintown.com/V.I.C' },
  { level: 2, name: 'Vado', url: 'http://bandsintown.com/Vado' },
  { level: 2, name: 'Vakill', url: 'http://bandsintown.com/Vakill' },
  { level: 2, name: 'Val Young', url: 'http://bandsintown.com/ValYoung' },
  { level: 2, name: 'Valete', url: 'http://bandsintown.com/Valete' },
  { level: 2, name: 'Vanilla Ice', url: 'http://bandsintown.com/VanillaIce' },
  { level: 2, name: 'Vast Aire', url: 'http://bandsintown.com/VastAire' },
  { level: 2, name: 'Verbal Jint', url: 'http://bandsintown.com/verbaljint' },
  {
    level: 2,
    name: 'Verse Simmonds',
    url: 'http://bandsintown.com/VerseSimmonds',
  },
  { level: 2, name: 'Vic Mensa', url: 'http://bandsintown.com/VicMensa' },
  {
    level: 2,
    name: 'Vince Staples',
    url: 'http://bandsintown.com/VinceStaples',
  },
  { level: 2, name: 'Vinnie Paz', url: 'http://bandsintown.com/VinniePaz' },
  { level: 2, name: 'Violent J', url: 'http://bandsintown.com/ViolentJ' },
  {
    level: 2,
    name: 'Waka Flocka Flame',
    url: 'http://bandsintown.com/WakaFlockaFlame',
  },
  { level: 2, name: 'Wale', url: 'http://bandsintown.com/Wale' },
  { level: 2, name: 'Warren G', url: 'http://bandsintown.com/WarrenG' },
  { level: 2, name: 'Watsky', url: 'http://bandsintown.com/Watsky' },
  { level: 2, name: 'Wax (rapper)', url: 'http://bandsintown.com/Wax' },
  { level: 2, name: 'WC', url: 'http://bandsintown.com/WC' },
  { level: 2, name: 'Webbie', url: 'http://bandsintown.com/Webbie' },
  {
    level: 2,
    name: 'Westside Gunn',
    url: 'http://bandsintown.com/WestsideGunn',
  },
  { level: 2, name: 'Will Smith', url: 'http://bandsintown.com/WillSmith' },
  { level: 2, name: 'will.i.am', url: 'http://bandsintown.com/will.i.am' },
  {
    level: 2,
    name: 'Willie the Kid',
    url: 'http://bandsintown.com/WillietheKid',
  },
  { level: 2, name: 'Willow Smith', url: 'http://bandsintown.com/WillowSmith' },
  {
    level: 2,
    name: 'Willy Northpole',
    url: 'http://bandsintown.com/willynorthpole',
  },
  { level: 2, name: 'Wish Bone', url: 'http://bandsintown.com/Wishbone' },
  { level: 2, name: 'Witchdoctor', url: 'http://bandsintown.com/Witchdoctor' },
  {
    level: 2,
    name: 'Wiz Khalifa[1]',
    url: 'http://bandsintown.com/WizKhalifa',
  },
  { level: 2, name: 'Wizkid', url: 'http://bandsintown.com/WizKid' },
  { level: 2, name: 'Wrekonize', url: 'http://bandsintown.com/Wrekonize' },
  { level: 2, name: 'Wyclef Jean', url: 'http://bandsintown.com/WyclefJean' },
  { level: 2, name: 'X-Raided', url: 'http://bandsintown.com/X-Raided' },
  { level: 2, name: 'XV', url: 'http://bandsintown.com/XV' },
  { level: 2, name: 'Xzibit', url: 'http://bandsintown.com/Xzibit' },
  {
    level: 2,
    name: 'XXXTENTACION',
    url: 'http://bandsintown.com/XXXTENTACION',
  },
  { level: 2, name: 'Ya Boy', url: 'http://bandsintown.com/YaBoy' },
  { level: 2, name: 'Yaki Kadafi', url: 'http://bandsintown.com/YakiKadafi' },
  {
    level: 2,
    name: 'Yazz The Greatest',
    url: 'http://bandsintown.com/YazzTheGreatest',
  },
  { level: 2, name: 'YC', url: 'http://bandsintown.com/Y.C.' },
  { level: 2, name: 'YDG', url: 'http://bandsintown.com/YDG' },
  { level: 2, name: 'Yelawolf', url: 'http://bandsintown.com/Yelawolf' },
  { level: 2, name: 'YFN Lucci', url: 'http://bandsintown.com/YfnLucci' },
  { level: 2, name: 'YG', url: 'http://bandsintown.com/YG' },
  { level: 2, name: 'Yo Gotti', url: 'http://bandsintown.com/YoGotti' },
  {
    level: 2,
    name: 'Yo Yo Honey Singh',
    url: 'http://bandsintown.com/Yo!Yo!HoneySingh',
  },
  { level: 2, name: 'Young Bleed', url: 'http://bandsintown.com/YoungBleed' },
  { level: 2, name: 'Young Buck', url: 'http://bandsintown.com/YoungBuck' },
  { level: 2, name: 'Young Chop', url: 'http://bandsintown.com/YoungChop' },
  { level: 2, name: 'Young Chris', url: 'http://bandsintown.com/YoungChris' },
  {
    level: 2,
    name: 'Young Dre the Truth',
    url: 'http://bandsintown.com/YOUNGDRETHETRUTH',
  },
  { level: 2, name: 'Young Dro', url: 'http://bandsintown.com/YoungDro' },
  {
    level: 2,
    name: 'Young Greatness',
    url: 'http://bandsintown.com/YoungGreatness',
  },
  { level: 2, name: 'Young Jeezy', url: 'http://bandsintown.com/YoungJeezy' },
  { level: 2, name: 'Young M.A', url: 'http://bandsintown.com/YoungM.A' },
  { level: 2, name: 'Young MC', url: 'http://bandsintown.com/YoungMC' },
  { level: 2, name: 'Young Noble', url: 'http://bandsintown.com/YoungNoble' },
  {
    level: 2,
    name: 'Young Scooter',
    url: 'http://bandsintown.com/YoungScooter',
  },
  { level: 2, name: 'Young Thug', url: 'http://bandsintown.com/YoungThug' },
  {
    level: 2,
    name: 'Your Old Droog',
    url: 'http://bandsintown.com/YourOldDroog',
  },
  { level: 2, name: 'Yukmouth', url: 'http://bandsintown.com/Yukmouth' },
  { level: 2, name: 'Yung Berg', url: 'http://bandsintown.com/YungBerg' },
  { level: 2, name: 'Yung Joc', url: 'http://bandsintown.com/YungJoc' },
  { level: 2, name: 'Yung L.A.', url: 'http://bandsintown.com/YungL.A.' },
  { level: 2, name: 'Yung Lean', url: 'http://bandsintown.com/YungLean' },
  { level: 2, name: 'Yung Wun', url: 'http://bandsintown.com/YungWun' },
  { level: 2, name: 'Z-Ro', url: 'http://bandsintown.com/Z-Ro' },
  { level: 2, name: 'Zaytoven', url: 'http://bandsintown.com/zaytoven' },
  { level: 2, name: 'Zebra Katz', url: 'http://bandsintown.com/ZEBRAKATZ' },
  { level: 2, name: 'Zico', url: 'http://bandsintown.com/Zico' },
];

export default secondaryArtists;
